/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodcity;

import static foodcity.Main.mdatee;
import static foodcity.Main.mtime;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Akila
 */
public class Attendence extends javax.swing.JFrame {

    /**
     * Creates new form Attendence
     */
    public Attendence() {
        initComponents();
       loaddate();
        setTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        it = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dt = new javax.swing.JLabel();
        eid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        asearch = new javax.swing.JButton();
        n = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ni = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        asave1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        idlist = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        it.setFont(new java.awt.Font("Prototype", 1, 56)); // NOI18N
        it.setForeground(new java.awt.Color(255, 255, 255));
        it.setText("20.08.46");
        getContentPane().add(it, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, 270, 90));

        jLabel4.setFont(new java.awt.Font("Prototype", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Time :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, -1, 40));

        jLabel3.setFont(new java.awt.Font("Prototype", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Date   :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 180, 40));

        dt.setFont(new java.awt.Font("Prototype", 1, 56)); // NOI18N
        dt.setForeground(new java.awt.Color(255, 255, 255));
        dt.setText("2016.07.12");
        getContentPane().add(dt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 370, 90));

        eid.setFont(new java.awt.Font("Prototype", 1, 18)); // NOI18N
        eid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eidActionPerformed(evt);
            }
        });
        eid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                eidKeyReleased(evt);
            }
        });
        getContentPane().add(eid, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 170, 30));

        jLabel2.setFont(new java.awt.Font("Prototype", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Employee ID  :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, 30));

        asearch.setBackground(new java.awt.Color(255, 153, 153));
        asearch.setText("S E A R C H");
        asearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asearchActionPerformed(evt);
            }
        });
        getContentPane().add(asearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 150, 40));

        n.setFont(new java.awt.Font("Prototype", 1, 18)); // NOI18N
        n.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 330, 30));

        jLabel10.setFont(new java.awt.Font("Prototype", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Name :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 80, 30));

        ni.setFont(new java.awt.Font("Prototype", 1, 18)); // NOI18N
        ni.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(ni, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 330, 30));

        jLabel11.setFont(new java.awt.Font("Prototype", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("NIC :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 50, 30));

        asave1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/esv.png"))); // NOI18N
        asave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asave1ActionPerformed(evt);
            }
        });
        getContentPane().add(asave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, 140, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "In Time", "Out Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 680, 190));

        idlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idlistMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(idlist);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 170, 60));

        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/ecan.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 310, 140, 40));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(714, 444, 60, 30));

        jLabel5.setBackground(new java.awt.Color(0, 153, 153));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/lol.png"))); // NOI18N
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 980, 560));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void asearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asearchActionPerformed
       if(eid.getText().length()==0){
        JOptionPane.showMessageDialog(this, "Please serch employee");
        eid.grabFocus();
        }else{
        try {
            ResultSet rs = db.search("select a.*,b.* from (emp a inner join login b on a.emp_id=b.emp_emp_id) where emp_id like '%" + eid.getText() + "%' and status='1'");
            if (rs.next()) {
                n.setText(rs.getString("fname")+" "+rs.getString("lname"));
                ni.setText(rs.getString("nic"));
                DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
                dtm.setRowCount(0);
                tblload(eid.getText());
                setTime();

            } else {
                JOptionPane.showMessageDialog(this, "This id is not valid", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
       }
    }//GEN-LAST:event_asearchActionPerformed

    private void asave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asave1ActionPerformed
   int loli=0;
   String ott="";
        if(eid.getText().length()==0){
        JOptionPane.showMessageDialog(this, "Please serch employee");
        
        eid.grabFocus();
        }else{
        try {
            ResultSet rs1 = db.search("select count(idattendance) as y from attendance");
            if (rs1.next()) {
                ResultSet rs5=db.search("select a.*,b.* from(emp a inner join login b on a.emp_id=b.emp_emp_id) where emp_id='"+eid.getText()+"'");
                if(rs5.next()){
                int x = Integer.parseInt(rs1.getString("y"));
                if (x == 0) {
                    db.iud("insert into attendance(date,in_time,emp_emp_id) values('" + dt.getText() + "','" + it.getText() + "','" + eid.getText() + "')");
                    JOptionPane.showMessageDialog(this, "Thank you");
                } else {
                    ResultSet rs = db.search("select * from attendance where emp_emp_id='" + eid.getText() + "'");
                    while (rs.next()) {
                        String d = rs.getString("date");
                        if (d.equalsIgnoreCase(dt.getText())) {
                           loli=1;
                            ott=rs.getString("out_time")+"1";
                        }
                    }
                    if(loli==1){
                   
                            System.out.println(ott);
                            String no="";
                            if(ott.length()==5){
                            db.iud("update attendance set out_time='" + it.getText() + "'");
                            JOptionPane.showMessageDialog(this, "Good Bye");
                            }else{
                            JOptionPane.showMessageDialog(this, "You are not allowed to entery today","Error",JOptionPane.ERROR_MESSAGE);
                            }
                    } else {
                            db.iud("insert into attendance(date,in_time,emp_emp_id) values('" + dt.getText() + "','" + it.getText() + "','" + eid.getText() + "')");
                            JOptionPane.showMessageDialog(this, "Thank you");
                        }
                }
                
                }else{
                JOptionPane.showMessageDialog(this, "Wrong employee id","Error",JOptionPane.ERROR_MESSAGE);
                eid.grabFocus();
                }

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
        dtm.setRowCount(0);
        tblload(eid.getText());
        }
          loaddate();
        eid.setText(null);
        n.setText(null);
        ni.setText(null);       
           idlist.setVisible(true);

            DefaultListModel model = new DefaultListModel();
                model.clear();
                idlist.setModel(model);


    }//GEN-LAST:event_asave1ActionPerformed

    private void eidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eidKeyReleased
        try {
            ResultSet rs = db.search("select a.*,b.* from (emp a inner join login b on a.emp_id=b.emp_emp_id) where emp_id like '%" + eid.getText() + "%' and status='1'");
            Vector v = new Vector();
            while (rs.next()) {
                v.add(rs.getString("emp_id"));
            }
            idlist.setListData(v);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_eidKeyReleased

    private void idlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idlistMouseClicked
        eid.setText(idlist.getSelectedValue().toString());
        idlist.setVisible(false);
    }//GEN-LAST:event_idlistMouseClicked

    private void eidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eidActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         idlist.setVisible(true);
         eid.setText(null);
         eid.grabFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Attendence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Attendence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Attendence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Attendence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Attendence().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton asave1;
    private javax.swing.JButton asearch;
    private javax.swing.JLabel dt;
    private javax.swing.JTextField eid;
    private javax.swing.JList idlist;
    private javax.swing.JLabel it;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel n;
    private javax.swing.JLabel ni;
    // End of variables declaration//GEN-END:variables

    private void loaddate() {
        
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        dt.setText(sdf.format(d));

    }

    private void tblload(String text) {
        try {
            ResultSet rs = db.search("select * from attendance where emp_emp_id='" + text + "'");
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString("date"));
                v.add(rs.getString("in_time"));
                v.add(rs.getString("out_time"));
                dtm.addRow(v);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void setTime() {
        
        Timer t = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");

                it.setText(sdf.format(d));
               
            }
        });
        t.start();
    }
}
