/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodcity;

import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TED
 */
public class checkpo extends javax.swing.JPanel {

    /**
     * Creates new form checkpo
     */
    public checkpo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        m = new javax.swing.JComboBox<String>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        y = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        mg = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item id", "Item name", "Qty", "Value"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 190, 320, 330));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Po id", "Date", "Need date", "Loger", "Total price", "Supplier ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 650, 330));

        m.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        jPanel1.add(m, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 110, 30));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Year  :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 60, 30));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" Month :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 70, 30));
        jPanel1.add(y, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 200, 30));

        jButton1.setBackground(new java.awt.Color(102, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/srch.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 60, 30));

        jLabel3.setFont(new java.awt.Font("Calibri Light", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("C H E C K   P U R C H A S E   O R D E R");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 490, 20));

        mg.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mg.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(mg, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 590, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/ll.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 540));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 540));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        dtm.setRowCount(0);
        int lol=0;
        if (y.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Please enter year", "Warning", JOptionPane.WARNING_MESSAGE);
            y.grabFocus();
        } else if (y.getText().length() != 4) {
            JOptionPane.showMessageDialog(this, "Please enter correct year", "Warning", JOptionPane.WARNING_MESSAGE);
            y.grabFocus();
        } else {
            String month = m.getSelectedItem().toString();
            String mn = "";
            if (month.equalsIgnoreCase("jan")) {
                mn = "01";
            } else if (month.equalsIgnoreCase("feb")) {
                mn = "02";
            } else if (month.equalsIgnoreCase("mar")) {
                mn = "03";
            } else if (month.equalsIgnoreCase("apr")) {
                mn = "04";
            } else if (month.equalsIgnoreCase("may")) {
                mn = "05";
            } else if (month.equalsIgnoreCase("jun")) {
                mn = "06";
            } else if (month.equalsIgnoreCase("jul")) {
                mn = "07";
            } else if (month.equalsIgnoreCase("aug")) {
                mn = "08";
            } else if (month.equalsIgnoreCase("sep")) {
                mn = "09";
            } else if (month.equalsIgnoreCase("oct")) {
                mn = "10";
            } else if (month.equalsIgnoreCase("nov")) {
                mn = "11";
            } else if (month.equalsIgnoreCase("dec")) {
                mn = "12";
            }
            String d = y.getText() + "-" + mn;
            try {
                ResultSet rs = db.search("select a.*,b.fname from(purchase_order a inner join emp b on a.emp_emp_id=b.emp_id) where date like '%" + d + "%'");
               
                while (rs.next()) {
                    mg.setText(null);
                    lol=1;
                    Vector v = new Vector();
                    v.add(rs.getString("po_id"));
                    v.add(rs.getString("date"));
                    v.add(rs.getString("need_date"));
                    v.add(rs.getString("fname"));
                    v.add(rs.getString("total"));
                    v.add(rs.getString("supplier_sup_id"));
                    dtm.addRow(v);
                }
                if(lol==0){
               mg.setText("No date in this date area. sorry!");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        try {
            DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
            dtm.setRowCount(0);
            int x=jTable2.getSelectedRow();
            ResultSet rs=db.search("select a.*,b.* from(purchase_order_has_item a  inner  join item b  on a.item_item_id=b.item_id) where purchase_order_po_id='"+jTable2.getValueAt(x, 0)+"'");
            while(rs.next()){
            Vector  v=new  Vector();
            v.add(rs.getString("item_id"));
             v.add(rs.getString("name"));
              v.add(rs.getString("qty"));
               v.add(rs.getString("tot"));
               dtm.addRow(v);
            }
        } catch (Exception e) {
        e.printStackTrace();
        }
    }//GEN-LAST:event_jTable2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JComboBox<String> m;
    private javax.swing.JLabel mg;
    private javax.swing.JTextField y;
    // End of variables declaration//GEN-END:variables
}
