/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodcity;

import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class empeddit extends javax.swing.JPanel {

    /**
     * Creates new form edditemp
     */
    public empeddit() {
        initComponents();
        clearAll();
        tblload();
        loadbnk();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        empid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        no = new javax.swing.JTextField();
        street = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tp_1 = new javax.swing.JTextField();
        tp_2 = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        eid = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        nic = new javax.swing.JTextField();
        post = new javax.swing.JComboBox();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        accno = new javax.swing.JTextField();
        dob = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        bname = new javax.swing.JComboBox();
        st = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, -1));

        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 20)); // NOI18N
        jLabel1.setText("E D D I T E   E M P L O Y E E");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setText("Employee ID:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));
        add(empid, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 128, 30));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 93, 30));

        jLabel3.setText("Employee ID:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel4.setText("First name:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel5.setText("Last name:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel6.setText("DOB");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel7.setText("NIC");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel8.setText("Gender");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jLabel9.setText("Post");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jLabel10.setText("No:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));

        jLabel11.setText("Street:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        jLabel12.setText("City  :");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, -1, -1));

        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });
        add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 144, -1));

        street.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetActionPerformed(evt);
            }
        });
        add(street, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 140, -1));
        add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 140, -1));

        jLabel13.setText("Mobile No:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, -1, -1));

        jLabel14.setText("Home No:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, -1, -1));

        jLabel15.setText("E_mail");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, -1, -1));
        add(tp_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 140, -1));
        add(tp_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 140, -1));
        add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, 140, -1));
        add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 140, -1));
        add(eid, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 140, 20));

        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });
        add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 140, -1));

        nic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicActionPerformed(evt);
            }
        });
        add(nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 140, -1));

        post.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(post, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 140, -1));

        buttonGroup1.add(male);
        male.setSelected(true);
        male.setText("Male");
        add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        buttonGroup1.add(female);
        female.setText("Female");
        add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 110, 130, 30));

        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 160, 130, 30));

        jLabel16.setText("Account_ Number");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, -1, -1));

        jLabel17.setText("Bank Name:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, -1));

        accno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accnoActionPerformed(evt);
            }
        });
        add(accno, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 150, -1));
        add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 140, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee_id", "First_Name", "DOB", "Nic", "Gender", "Post", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 1000, 130));

        jButton4.setText("Deactiov");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 330, 130, 40));

        jButton5.setText("Activate");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, 130, 40));

        add(bname, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 150, -1));
        add(st, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 250, 70, 20));

        jLabel19.setText("Status :");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, -1, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           try {
            ResultSet rs=db.search("select a.*,b.*,c.* from ((emp a inner join emp_address b on a.emp_id=b.emp_emp_id)"
                    + "inner join emp_contact c on a.emp_id=c.emp_emp_id)where a.emp_id='"+empid.getText()+"'");
            if(rs.next()){
                
               
                eid.setText(rs.getString("emp_id"));
                fname.setText(rs.getString("fname"));
                lname.setText(rs.getString("lname"));
                dob.setDate(rs.getDate("dob"));
                nic.setText(rs.getString("nic"));
                String gender=rs.getString("gender");
                if(gender.equals("Male")){
                male.setSelected(true);
                }else{
                female.setSelected(true);
                }
//                posst.(rs.getString("position"));
                tp_1.setText(rs.getString("tp1"));
                tp_2.setText(rs.getString("tp2"));
                email.setText(rs.getString("mail"));
                no.setText(rs.getString("no"));
                street.setText(rs.getString("street"));
                city.setText(rs.getString("city"));
                bname.setSelectedItem(rs.getString("bank_name"));
                accno.setText(rs.getString("bank_account"));
                st.setText(rs.getString("status"));
                
                
            }else{
                JOptionPane.showMessageDialog(this, "Wrong employee id...","Error",JOptionPane.ERROR_MESSAGE);
                empid.setText(null);
                empid.grabFocus();
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void streetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetActionPerformed

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noActionPerformed

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void nicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            updata();
            DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
            dtm.setRowCount(0);
            tblload();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void accnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accnoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      clearAll();
      tblload();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       int x=jTable1.getSelectedRow();
        String id=jTable1.getValueAt(x, 0).toString();
          try {
            ResultSet rs=db.search("select a.*,b.*,c.* from ((emp a inner join emp_address b on a.emp_id=b.emp_emp_id)"
                    + "inner join emp_contact c on a.emp_id=c.emp_emp_id)where emp_id='"+id+"'");
            if(rs.next()){
                
               
                eid.setText(rs.getString("emp_id"));
                fname.setText(rs.getString("fname"));
                lname.setText(rs.getString("lname"));
                dob.setDate(rs.getDate("dob"));
                nic.setText(rs.getString("nic"));
                String gender=rs.getString("gender");
                if(gender.equals("Male")){
                male.setSelected(true);
                }else{
                female.setSelected(true);
                }
//                posst.(rs.getString("position"));
                tp_1.setText(rs.getString("tp1"));
                tp_2.setText(rs.getString("tp2"));
                email.setText(rs.getString("mail"));
                no.setText(rs.getString("no"));
                street.setText(rs.getString("street"));
                city.setText(rs.getString("city"));
                if(rs.getString("bank_bank_id").length()==0){
                }else{
                    ResultSet rs2=db.search("select * from bank bank_id='"+rs.getString("bank_bank_id")+"'");
                    if(rs2.next()){
                    
                    }
                bname.setSelectedItem(rs.getString("bank_name"));
                }
                
                accno.setText(rs.getString("bank_account"));
                 st.setText(rs.getString("status"));
                
            }else{
                JOptionPane.showMessageDialog(this, "Wrong employee id...","Error",JOptionPane.ERROR_MESSAGE);
                empid.setText(null);
                empid.grabFocus();
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       if(st.getText().length()==0){
           JOptionPane.showMessageDialog(this, "Please search item first","Error",JOptionPane.ERROR_MESSAGE);
       }else if(st.getText().equals('1')){
        JOptionPane.showMessageDialog(this, "Already activated");
       
       }else{
        try {
           db.iud("update employee set status='1' where emp_id='"+eid.getText()+"'");
           JOptionPane.showMessageDialog(this, "Success");
        } catch (Exception e) {
        e.printStackTrace();
        }
       }
       clearAll();
       tblload();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(st.getText().length()==0){
           JOptionPane.showMessageDialog(this, "Please search item first","Error",JOptionPane.ERROR_MESSAGE);
       }else if(st.getText().equals('0')){
        JOptionPane.showMessageDialog(this, "Already Deactivated");
       
       }else{
        try {
           db.iud("update employee set status='0' where emp_id='"+eid.getText()+"'");
           JOptionPane.showMessageDialog(this, "Success");
        } catch (Exception e) {
        e.printStackTrace();
        }
       }
        clearAll();
        tblload();
        
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accno;
    private javax.swing.JComboBox bname;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField city;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JLabel eid;
    private javax.swing.JTextField email;
    private javax.swing.JTextField empid;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lname;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField nic;
    private javax.swing.JTextField no;
    private javax.swing.JComboBox post;
    private javax.swing.JLabel st;
    private javax.swing.JTextField street;
    private javax.swing.JTextField tp_1;
    private javax.swing.JTextField tp_2;
    // End of variables declaration//GEN-END:variables

    private void updata() {
    
         try {
             Date d = dob.getDate();
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                    String dat = sdf.format(d);
                    String gen = "";
                    if (male.isSelected()) {
                        gen = "male";
                    } else {
                        gen = "female";
                    }
             ResultSet rs=db.search("select * from bank where Name='"+bname.getSelectedItem()+"'");
                if(rs.next()){
                db.iud("update emp set fname='"+fname.getText()+"',lname='"+lname.getText()+"',dob='"+dat+"',nic='"+nic.getText()+"',gender='"+gen+"',status='1',bank_account='"+accno.getText()+"',post='"+post.getSelectedItem()+"',bank_bank_id='"+rs.getString("bank_id")+"' where emp_id='"+eid.getText()+"'");
                db.iud("update emp_address set no='"+no.getText()+"',street='"+street.getText()+"',city='"+city.getText()+"' where emp_emp_id='"+eid.getText()+"'");
                db.iud("update emp_contact set tp1='"+tp_1.getText()+"',tp2='"+tp_2.getText()+"',mail='"+email.getText()+"' where emp_emp_id='"+eid.getText()+"'");
                JOptionPane.showMessageDialog(this, "You are success");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
    }

    private void clearAll() {
         fname.setText(null);
       lname.setText(null);
       dob.setDate(null);
       nic.setText(null);
       male.setSelected(true);
       accno.setText(null);
       post.setSelectedItem(true);
      
       no.setText(null);
       street.setText(null);
       city.setText(null);
       tp_1.setText(null);
       tp_2.setText(null);
       email.setText(null);
       st.setText(null);
    }

    private void tblload() {
        try {
            ResultSet rs=db.search("select * from emp");
            DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
            dtm.setRowCount(0);
           
            while(rs.next()){
                
                Vector v=new Vector();
                v.add(rs.getString("emp_id"));
                v.add(rs.getString("fname"));
                v.add(rs.getString("dob"));
                v.add(rs.getString("nic"));
                v.add(rs.getString("gender"));
                v.add(rs.getString("post"));
              
                 v.add(rs.getString("status"));
                dtm.addRow(v);
            }
        } catch (Exception e) {
        e.printStackTrace();
        }
   
    }

    private void loadbnk() {
        try {
            ResultSet  rs=(ResultSet) db.search("select * from bank");
            while(rs.next()){
           bname.addItem(rs.getString("Name"));
            }
        } catch (Exception e) {
        e.printStackTrace();
        } }

    
}
