/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodcity;

import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Probosha
 */
public class forget_password extends javax.swing.JFrame {

    String q1="";
        String q2="";
        String q3="";
        String id="";
    public forget_password() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        a = new javax.swing.JComboBox();
        an1 = new javax.swing.JTextField();
        an2 = new javax.swing.JTextField();
        b = new javax.swing.JComboBox();
        an3 = new javax.swing.JTextField();
        c = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 210, 30));

        jLabel1.setText("User Name :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 80, 30));

        getContentPane().add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 490, 20));
        getContentPane().add(an1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 490, -1));
        getContentPane().add(an2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 490, -1));

        getContentPane().add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 490, 20));
        getContentPane().add(an3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 490, -1));

        getContentPane().add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 490, 20));

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("C h e c k");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 180, 40));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/srch.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 60, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("   G i v e  Y O U R   A N S W E R");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 330, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("F O R G E T    P A S S W O R D");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 330, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/lol1.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        int x=0;
        try {
            ResultSet rs=db.search("select * from login");
            if(rs.next()){
                 id=rs.getString("emp_emp_id");
            ResultSet rss=db.search("select * from emp_has_forget_password where emp_emp_id='"+id+"'");
            while(rss.next()){
                if(x==0){
                q1=rss.getString("forget_password_question_id");
                }else if(x==1){
                q2=rss.getString("forget_password_question_id");
                }else if(x==2){
                q3=rss.getString("forget_password_question_id");
                }
                x++;
           
            }
            x=0;
            
            ResultSet rs1=db.search("select * from forget_password where question_id='"+q1+"'");
            if(rs1.next()){
            a.addItem(rs1.getString("question"));
            }ResultSet rs2=db.search("select * from forget_password where question_id='"+q2+"'");
            if(rs2.next()){
            b.addItem(rs2.getString("question"));
            }ResultSet rs3=db.search("select * from forget_password where question_id='"+q3+"'");
            if(rs3.next()){
            c.addItem(rs3.getString("question"));
            }
            
            
            
            }
        } catch (Exception e) {
        e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String a1="";
        String a2="";
        String a3="";
        int lol=0;
        try {
            ResultSet rs=db.search("select * from emp_has_forget_password where emp_emp_id='"+id+"'");
            while(rs.next()){
            if(lol==0){
            a1=rs.getString("answer");
            }else if(lol==1){
            a2=rs.getString("answer");
            }else if(lol==2){
            a3=rs.getString("answer");
            }
            lol++;
            }
            if(a1.equalsIgnoreCase(an1.getText())){
            if(a2.equalsIgnoreCase(an2.getText())){
            if(a3.equalsIgnoreCase(an3.getText())){
            pwdrecovery p=new pwdrecovery();
            p.setVisible(true);
            this.dispose();
            }
            }
            }else{
                JOptionPane.showMessageDialog(this,"Wrong answer","ERROR",JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
        e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forget_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forget_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forget_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forget_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forget_password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox a;
    private javax.swing.JTextField an1;
    private javax.swing.JTextField an2;
    private javax.swing.JTextField an3;
    private javax.swing.JComboBox b;
    private javax.swing.JComboBox c;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

   
}
