/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodcity;

import java.awt.Color;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

public class invoice extends javax.swing.JPanel {

    int tblclicked;

    public invoice() {
        initComponents();
        tblclicked = 0;
        gencusid();
        geninvid();
        jButton2.setEnabled(false);
        jButton7.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        invid = new javax.swing.JLabel();
        itemid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        up = new javax.swing.JLabel();
        qty = new javax.swing.JTextField();
        t = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        dis = new javax.swing.JTextField();
        dp = new javax.swing.JLabel();
        st = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        invitem = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        sbtt = new javax.swing.JLabel();
        payment = new javax.swing.JTextField();
        invdiscount = new javax.swing.JTextField();
        balance = new javax.swing.JLabel();
        dpr = new javax.swing.JLabel();
        nettotal = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        cid = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        cn = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        ct = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        iidlist = new javax.swing.JList();
        eid = new javax.swing.JLabel();
        mg = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Prototype", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("I N V O I C E");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 151, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Invoice id :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Item Id:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 30));

        invid.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        invid.setForeground(new java.awt.Color(255, 255, 255));
        add(invid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 90, 30));

        itemid.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        itemid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                itemidKeyReleased(evt);
            }
        });
        add(itemid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 110, 30));

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/srch.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 60, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Name:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 70, 30));

        name.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 140, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Unite Price:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, -1, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Qty:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 70, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, -1, 30));

        up.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        up.setForeground(new java.awt.Color(255, 255, 255));
        add(up, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 140, 30));

        qty.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qtyKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qtyKeyTyped(evt);
            }
        });
        add(qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 140, 30));

        t.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        t.setForeground(new java.awt.Color(255, 255, 255));
        add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 140, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Discount:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 180, 70, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Disprise:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, -1, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Subtotal:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, -1, 30));

        dis.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        dis.setText("0");
        dis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disActionPerformed(evt);
            }
        });
        dis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                disKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                disKeyTyped(evt);
            }
        });
        add(dis, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 180, 140, 30));

        dp.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        dp.setForeground(new java.awt.Color(255, 255, 255));
        dp.setText("0");
        add(dp, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 220, 140, 30));

        st.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        st.setForeground(new java.awt.Color(255, 255, 255));
        add(st, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 260, 140, 30));

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/addtv.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 290, 90, 50));

        invitem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item_id", "Name", "U.price", "Qty", "Total", "Discount", "Disprice", "Subprice"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        invitem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                invitemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(invitem);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 790, 190));

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/ed.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 370, 160, 40));

        jButton4.setBackground(new java.awt.Color(255, 51, 51));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/rm.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 430, 160, 40));

        jButton5.setBackground(new java.awt.Color(255, 51, 51));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/cltb.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 500, 160, 40));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Subtotal");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, -1, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Payment");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 570, -1, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Discount:");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, -1, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Balance:");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 620, -1, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Disprice:");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 570, 80, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Net Total:");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 610, -1, 30));

        sbtt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        sbtt.setForeground(new java.awt.Color(255, 255, 255));
        add(sbtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 570, 140, 30));

        payment.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentActionPerformed(evt);
            }
        });
        payment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                paymentKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                paymentKeyTyped(evt);
            }
        });
        add(payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 570, 140, 30));

        invdiscount.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        invdiscount.setText("0");
        invdiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invdiscountActionPerformed(evt);
            }
        });
        invdiscount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                invdiscountKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                invdiscountKeyTyped(evt);
            }
        });
        add(invdiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 620, 140, 30));

        balance.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        balance.setForeground(new java.awt.Color(255, 255, 255));
        add(balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 620, 130, 30));

        dpr.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        dpr.setForeground(new java.awt.Color(255, 255, 255));
        dpr.setText("0");
        add(dpr, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 570, 120, 30));

        nettotal.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        nettotal.setForeground(new java.awt.Color(255, 255, 255));
        add(nettotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 610, 120, 30));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Customer  id:");
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 120, 20));

        cid.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cid.setForeground(new java.awt.Color(255, 255, 255));
        add(cid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 110, 30));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Customer Name:");
        add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        cn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnActionPerformed(evt);
            }
        });
        add(cn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 120, 30));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Customer TP:");
        add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, 20));

        ct.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        add(ct, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 120, 30));

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 610, 70));

        jButton7.setBackground(new java.awt.Color(255, 0, 0));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/pay.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 610, 150, 60));

        iidlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iidlistMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(iidlist);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 170, 90));

        eid.setForeground(new java.awt.Color(255, 255, 255));
        add(eid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 120, 30));

        mg.setForeground(new java.awt.Color(255, 0, 0));
        add(mg, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 140, 20));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/cncl.png"))); // NOI18N
        jButton8.setContentAreaFilled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 610, 70, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/bck.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 690));
    }// </editor-fold>//GEN-END:initComponents

    private void disActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        DefaultTableModel dtm = (DefaultTableModel) invitem.getModel();
        dtm.setRowCount(0);
        tblclicked = 0;
    }//GEN-LAST:event_jButton5ActionPerformed

    private void cnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        loading();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void qtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyKeyReleased
            try {
            ResultSet rs = db.search("select * from stock where item_item_id='" + itemid.getText() + "'");
            if (rs.next()) {
                double qt = Double.parseDouble(rs.getString("qty"));
                double gvqt = Double.parseDouble(qty.getText());
                if (qt >= gvqt) {
                    mg.setText("Available");
                    mg.setForeground(Color.green);
                    jButton2.setEnabled(true);
                } else {
                    mg.setText("Out of stock");
                    mg.setForeground(Color.red);
                    jButton2.setEnabled(false);
                }

            }

        } catch (Exception e) {
        }

        if (up.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Please enter item", "Error", JOptionPane.ERROR_MESSAGE);
            itemid.grabFocus();
        } else {
            double qt = 0;
            if (qty.getText().length() == 0) {
            } else {
                qt = Double.parseDouble(qty.getText());
            }
            double upr = Double.parseDouble(up.getText());
            double tot = qt * upr;
            t.setText("" + tot);
            double disc = 0;
            if (dis.getText().length() == 0) {

            } else {
                disc = Double.parseDouble(dis.getText());
            }
            double disv = tot * disc / 100;
            dp.setText("" + disv);
            double tt = tot - disv;
            st.setText("" + tt);
        }
    }//GEN-LAST:event_qtyKeyReleased

    private void qtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyKeyTyped
        qty.setBackground(Color.WHITE);
        char c = evt.getKeyChar();
        if (c >= '0' && c <= '9') {

        } else {
            evt.consume();

        }
    }//GEN-LAST:event_qtyKeyTyped

    private void disKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_disKeyReleased
        double d;
        double to;
        if (dis.getText().length() == 0) {
            d = 0;
            to = Double.parseDouble(t.getText());
            double disp = d * to / 100;
            dp.setText("" + disp);
            double nettot = to - disp;
            st.setText("" + nettot);
        } else {
            d = Double.parseDouble(dis.getText());
            to = Double.parseDouble(t.getText());
            double disp = d * to / 100;
            dp.setText("" + disp);
            double nettot = to - disp;
            st.setText("" + nettot);
        }
    }//GEN-LAST:event_disKeyReleased

    private void disKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_disKeyTyped
        char c = evt.getKeyChar();
        if (c >= '0' && c <= '9') {

        } else {
            evt.consume();

        }
    }//GEN-LAST:event_disKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int x = invitem.getRowCount();
        int xa = 0;
        if (itemid.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Please enter item id", "Error", JOptionPane.ERROR_MESSAGE);
            itemid.grabFocus();
            itemid.setBackground(Color.red);
        } else if (qty.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Please enter qty", "Error", JOptionPane.ERROR_MESSAGE);
            qty.grabFocus();
            qty.setBackground(Color.red);
        } else {
            if (x == 0) {
                double subtotal = 0;
                DefaultTableModel dtm = (DefaultTableModel) invitem.getModel();
                Vector v = new Vector();
                v.add(itemid.getText());
                v.add(name.getText());
                v.add(up.getText());
                v.add(qty.getText());
                v.add(t.getText());
                v.add(dis.getText());
                v.add(dp.getText());
                v.add(st.getText());
                dtm.addRow(v);
            } else {

                for (int i = 0; i < invitem.getRowCount(); i++) {
                    String id = invitem.getValueAt(i, 0).toString();
                    if (id.equalsIgnoreCase(itemid.getText())) {
                        System.out.println("awll");
                        xa = 1;
                        double qt = Double.parseDouble(invitem.getValueAt(i, 3).toString());
                        double nwqty = Double.parseDouble(qty.getText());
                        nwqty = nwqty + qt;
                        invitem.setValueAt(nwqty, i, 3);

                        double pr = Double.parseDouble(up.getText());
                        double value = nwqty * pr;
                        invitem.setValueAt(value, i, 4);

                        double diss = Double.parseDouble(invitem.getValueAt(i, 5).toString());
                        double disv = value * diss / 100;
                        invitem.setValueAt(disv, i, 6);

                        double tot = value - disv;
                        invitem.setValueAt(tot, i, 7);
                    }

                }
                if (xa == 0) {

                    DefaultTableModel dtm = (DefaultTableModel) invitem.getModel();
                    Vector v = new Vector();
                    v.add(itemid.getText());
                    v.add(name.getText());
                    v.add(up.getText());
                    v.add(qty.getText());
                    v.add(t.getText());
                    v.add(dis.getText());
                    v.add(dp.getText());
                    v.add(st.getText());
                    dtm.addRow(v);
                }

            }
            xa = 0;
            double dcv = 0;
            double to = 0;
            double stt = 0;
            double diss = 0;
            for (int i = 0; i < invitem.getRowCount(); i++) {
                double tot = Double.parseDouble(invitem.getValueAt(i, 7).toString());
                diss = diss + tot;
            }
            sbtt.setText("" + diss);
            if(invdiscount.getText().length()==0){
                nettotal.setText(""+diss);
            }else{
            dcv=Double.parseDouble(invdiscount.getText());
            stt=Double.parseDouble(sbtt.getText());
            to=stt-stt*dcv/100;
            nettotal.setText(""+to);
            }

            itemid.setText(null);
            name.setText(null);
            up.setText(null);
            qty.setText(null);
            t.setText(null);
            dis.setText(""+0);
            dp.setText(""+0);
            st.setText(null);
            
        }
        jButton2.setEnabled(false);


    }//GEN-LAST:event_jButton2ActionPerformed

    private void invdiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invdiscountActionPerformed
        double d1 = Double.parseDouble(sbtt.getText());
        double d2 = Double.parseDouble(invdiscount.getText());
        double d3 = d1 * (100 - d2) / 100;
        nettotal.setText("" + d3);
        payment.grabFocus();
    }//GEN-LAST:event_invdiscountActionPerformed

    private void paymentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paymentKeyReleased
        if (nettotal.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Please add items", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            double nt = Double.parseDouble(nettotal.getText());
            double pay = 0;
            if (payment.getText().length() == 0) {
            } else {
                pay = Double.parseDouble(payment.getText());
            }
            double bal = pay - nt;
            if(bal>=0){
            jButton7.setEnabled(true);
            }else{
            jButton7.setEnabled(false);
            }
            balance.setText("" + bal);

        }
    }//GEN-LAST:event_paymentKeyReleased

    private void invdiscountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_invdiscountKeyReleased

        if (sbtt.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Please add item", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            double st = Double.parseDouble(sbtt.getText().toString());
            double dis = 0;
            if (invdiscount.getText().length() == 0) {

            } else {
                dis = Double.parseDouble(invdiscount.getText().toString());
            }
            double disv = st * dis / 100;
            dpr.setText("" + disv);
            double nt = st - disv;
            nettotal.setText("" + nt);
        }
    }//GEN-LAST:event_invdiscountKeyReleased

    private void invdiscountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_invdiscountKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_invdiscountKeyTyped

    private void paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentActionPerformed
        double d1 = Double.parseDouble(nettotal.getText());
        double d2 = Double.parseDouble(payment.getText());
        if (d1 <= d2) {
            balance.setText("" + (d2 - d1));
            balance.grabFocus();
        }
    }//GEN-LAST:event_paymentActionPerformed

    private void paymentKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paymentKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (tblclicked == 1) {
            int x = invitem.getSelectedRow();
            itemid.setText(invitem.getValueAt(x, 0).toString());
            name.setText(invitem.getValueAt(x, 1).toString());
            up.setText(invitem.getValueAt(x, 2).toString());
            qty.setText(invitem.getValueAt(x, 3).toString());
            t.setText(invitem.getValueAt(x, 4).toString());
            dis.setText(invitem.getValueAt(x, 5).toString());
            dp.setText(invitem.getValueAt(x, 6).toString());
            st.setText(invitem.getValueAt(x, 7).toString());
        }
        tblclicked = 0;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (tblclicked == 1) {
            int x = invitem.getSelectedRow();
            DefaultTableModel dtm = (DefaultTableModel) invitem.getModel();
            dtm.removeRow(x);
        }
        tblclicked = 0;
    }//GEN-LAST:event_jButton4ActionPerformed

    private void itemidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemidKeyReleased
        try {
            ResultSet rs = db.search("select * from item where item_id like '%" + itemid.getText() + "%' and status='1'");
            Vector v = new Vector();
            while (rs.next()) {

                v.add(rs.getString("item_id"));

            }
            iidlist.setListData(v);
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_itemidKeyReleased

    private void iidlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iidlistMouseClicked
        String nam = iidlist.getSelectedValue().toString();
        itemid.setText(nam);
        try {
            ResultSet rs = db.search("select * from item where item_id='" + nam + "'");
            if (rs.next()) {
                name.setText(rs.getString("name"));
                up.setText(rs.getString("sale_price"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_iidlistMouseClicked

    private void invitemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invitemMouseClicked
        tblclicked = 1;

    }//GEN-LAST:event_invitemMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (balance.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Something is wrong", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                Date d = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String date = sdf.format(d);
                SimpleDateFormat sdf1 = new SimpleDateFormat("HH:mm:ss");
                String time = sdf1.format(d);
                double st = Double.parseDouble(sbtt.getText());
                double disc = Double.parseDouble(invdiscount.getText());
                double discv = Double.parseDouble(dpr.getText());
                double mt = Double.parseDouble(nettotal.getText());
                db.iud("insert into customer(cus_id,name,tp) values('" + cid.getText() + "','" + cn.getText() + "','" + ct.getText() + "')");
                db.iud("insert into invoice(inv_id,date,time,subtot,discount,dis_value,nettot,emp_emp_id,customer_cus_id) values"
                        + "('" + invid.getText() + "','" + date + "','" + time + "','" + st + "','" + disc + "','" +discv+ "','" + mt + "','" + log.empido + "','" + cid.getText() + "') ");

                for (int i = 0; i < invitem.getRowCount(); i++) {
                    String id = invitem.getValueAt(i, 0).toString();
                    double qt = Double.parseDouble(invitem.getValueAt(i, 3).toString());
                    double tt = Double.parseDouble(invitem.getValueAt(i, 4).toString());
                    //double discs = Double.parseDouble(invitem.getValueAt(i, 5).toString());
                    double dv = Double.parseDouble(invitem.getValueAt(i, 6).toString());
                    double nnt = Double.parseDouble(invitem.getValueAt(i, 7).toString());
                    db.iud("insert into invoice_has_item (invoice_inv_id,item_item_id,qty,total,disc,disc_value,sub_tot) values"
                            + "('" + invid.getText() + "','" + id + "','" + qt + "','" + tt + "','" +invitem.getValueAt(i, 5).toString()+ "','" + dv + "','" + nnt + "')");
                    ResultSet rs = db.search("select * from stock where item_item_id='" + id + "'");
                    if (rs.next()) {
                        System.out.println("55555");
                        double avbqty = Double.parseDouble(rs.getString("qty"));
                        double newqt = avbqty - qt;
                        db.iud("update stock set qty='" + newqt + "' where item_item_id='" + id + "' ");

                        ResultSet rs2 = db.search("select count(idmoney_account) as x from money_account ");
                        if (rs2.next()) {
                          
                            ResultSet rs3 = db.search("select * from money_account ");
                            if (rs3.next()) {
                                
                                int x = Integer.parseInt(rs2.getString("x"));
                                double amountt = 0;
                                if (x == 0) {
                                    System.out.println("owl"); 
                                    db.iud("insert into money_account(idmoney_account,amount) values('1','" + mt + "')");
                              
                                    } else {
                                    
                                    double value = Double.parseDouble(rs3.getString("amount"));
                                    amountt = value + mt;
                                    db.iud("update money_account set amount='" + amountt + "' where idmoney_account='1'");
                                }
                            }else{
                              System.out.println("owl"); 
                                    db.iud("insert into money_account(idmoney_account,amount) values('1','" + mt + "')");
                               }
                        }

                    }

                }
                reporta();
                JOptionPane.showMessageDialog(this, "success");

            } catch (Exception e) {
                e.printStackTrace();
            }
            DefaultTableModel dtm = (DefaultTableModel) invitem.getModel();
            dtm.setRowCount(0);
            sbtt.setText(null);
            invdiscount.setText(""+0);
            dpr.setText(""+0);
            nettotal.setText(null);
            payment.setText(null);
            balance.setText(null);
            geninvid();
            gencusid();
        }
        jButton7.setEnabled(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Main.mp.removeAll();
        Main.mp.revalidate();
        run r=new run();
        Main.mp.add(r);
    }//GEN-LAST:event_jButton8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel balance;
    private javax.swing.JLabel cid;
    private javax.swing.JTextField cn;
    private javax.swing.JTextField ct;
    private javax.swing.JTextField dis;
    private javax.swing.JLabel dp;
    private javax.swing.JLabel dpr;
    private javax.swing.JLabel eid;
    private javax.swing.JList iidlist;
    private javax.swing.JTextField invdiscount;
    private javax.swing.JLabel invid;
    private javax.swing.JTable invitem;
    private javax.swing.JTextField itemid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel mg;
    private javax.swing.JLabel name;
    private javax.swing.JLabel nettotal;
    private javax.swing.JTextField payment;
    private javax.swing.JTextField qty;
    private javax.swing.JLabel sbtt;
    private javax.swing.JLabel st;
    private javax.swing.JLabel t;
    private javax.swing.JLabel up;
    // End of variables declaration//GEN-END:variables

    private void gencusid() {

        try {
            ResultSet rs = db.search("select count(cus_id) as x from customer");

            if (rs.next()) {

                int x = Integer.parseInt(rs.getString("x"));
                x++;
                if (x < 10) {

                    cid.setText("CUS00" + x);
                } else if (x < 100) {

                    cid.setText("CUS0" + x);
                } else {

                    cid.setText("CUS" + x);
                }

            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void geninvid() {

        try {
            ResultSet rs = db.search("select count(inv_id) as x from invoice");

            if (rs.next()) {

                //string ekak int kalannaa
                int x = Integer.parseInt(rs.getString("x"));
                x++;
                if (x < 10) {

                    invid.setText("INV00" + x);
                } else if (x < 100) {

                    invid.setText("INV0" + x);
                } else {

                    invid.setText("INV" + x);
                }

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loading() {
        try {
            ResultSet rs = db.search("select * from item where item_id='" + itemid.getText() + "' and status='1'");
            if (rs.next()) {
                name.setText(rs.getString("name"));
                up.setText(rs.getString("sale_price"));
            } else {
                JOptionPane.showMessageDialog(this, "Wrong item id", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void reporta() {
        try {
            String path="C:\\ProgramData\\supercity\\2\\invoice.jrxml";
            JasperReport jr=JasperCompileManager.compileReport(path);
            Map<String,Object> m=new HashMap<>();
            m.put("id", invid.getText());
            JasperPrint jp=JasperFillManager.fillReport(jr, m,db.con());
            JasperViewer.viewReport(jp,false);
        } catch (Exception e) {
        e.printStackTrace();
        }
 
    
    }
}
