/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodcity;

import java.awt.Color;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import static javax.management.Query.not;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.derby.impl.drda.ReEncodedInputStream;

/**
 *
 * @author User
 */
public class item_add extends javax.swing.JPanel {

    /**
     * Creates new form item_add
     */
    int clicked;

    public item_add() {
        initComponents();
        iname.grabFocus();
        clicked = 0;
        genitmid();
        genbid();
        tablload();
        loadtp();
        loadbnd();
        loadbdg();
        btnfalse();
        avbt.setEnabled(true);
        nme.setEditable(false);
        jButton7.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sta = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        iname = new javax.swing.JTextField();
        uprice = new javax.swing.JTextField();
        sprice = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        iid = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        st = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        bname = new javax.swing.JTextField();
        avbt = new javax.swing.JComboBox<>();
        bid = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        nme = new javax.swing.JTextField();
        bdg = new javax.swing.JLabel();
        bnd = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("I T E M    R E G I  S  T R A T I O N");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 270, -1));

        jLabel2.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Stock ID");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        sta.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        sta.setForeground(new java.awt.Color(255, 255, 255));
        add(sta, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 80, 30));

        jLabel5.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Brand");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, -1, 20));

        iname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inameActionPerformed(evt);
            }
        });
        add(iname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 160, 30));

        uprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upriceActionPerformed(evt);
            }
        });
        uprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                upriceKeyTyped(evt);
            }
        });
        add(uprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 160, 30));

        sprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                spriceKeyTyped(evt);
            }
        });
        add(sprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 160, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Unite Price", "Sale Price", "Brand", "Badge", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 1010, 190));

        jButton5.setBackground(new java.awt.Color(255, 255, 0));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/esv.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 280, 140, 40));

        jButton6.setBackground(new java.awt.Color(204, 0, 0));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/ecan.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 280, 140, 40));

        iid.setForeground(new java.awt.Color(255, 255, 255));
        iid.setText("jLabel6");
        add(iid, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 120, 30));

        jLabel6.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Item ID");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        st.setForeground(new java.awt.Color(255, 255, 255));
        add(st, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 110, 30));

        jLabel7.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Item Name");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/podisv.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, 80, 30));
        add(bname, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, 110, 30));

        add(avbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 110, 120, -1));

        bid.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        bid.setForeground(new java.awt.Color(255, 255, 255));
        add(bid, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 110, 30));

        jLabel9.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Brand Name");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, -1, 30));

        jButton7.setBackground(new java.awt.Color(255, 255, 0));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/podisv.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 210, 80, 30));
        add(nme, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 170, 120, 30));

        bdg.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        bdg.setForeground(new java.awt.Color(255, 255, 255));
        add(bdg, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 160, 30));

        add(bnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 160, 30));

        jLabel11.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Unite Price");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        jLabel12.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Name :");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 170, -1, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("*");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 20, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 0, 0));
        jLabel15.setText("*");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setText("*");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, -1, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 0, 0));
        jLabel18.setText("*");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, -1, 30));

        jLabel19.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Sale Price");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, 20));

        jButton2.setBackground(new java.awt.Color(255, 255, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/edac.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 140, 40));

        jButton3.setBackground(new java.awt.Color(255, 255, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/eact.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 140, 40));

        jButton4.setBackground(new java.awt.Color(255, 255, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/eup.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 140, 40));

        jLabel8.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Badge NO :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 30));

        jLabel10.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Status  :");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, -1, 30));

        jLabel17.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add New Brand", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 240, 120));

        jLabel13.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Brand Id :");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, -1, 20));

        jLabel20.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Avb type :");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 110, -1, 20));

        jButton9.setBackground(new java.awt.Color(204, 0, 0));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/podicancl.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 210, 80, -1));

        jButton8.setBackground(new java.awt.Color(0, 102, 102));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton8.setText(" Add New Type");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(905, 140, 120, -1));

        jLabel14.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Type", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 90, 220, 160));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/ll.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 540));
    }// </editor-fold>//GEN-END:initComponents

    private void upriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upriceActionPerformed
        sprice.grabFocus();
    }//GEN-LAST:event_upriceActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        checkbrnd();

        sve();
        tablload();
        genitmid();
      
        checkbrnd();
        loadbdg();

        clr();

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int x=jTable1.getSelectedRow();
        iid.setText(jTable1.getValueAt(x,0).toString());
        iname.setText(jTable1.getValueAt(x,1).toString());
        uprice.setText(jTable1.getValueAt(x,2).toString());
        sprice.setText(jTable1.getValueAt(x,3).toString());
        bnd.setSelectedItem(jTable1.getValueAt(x,4).toString());
        bdg.setText(jTable1.getValueAt(x,5).toString());
         sta.setText(jTable1.getValueAt(x,6).toString());
        btntrue();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       loadbdg();
        tablload();
        genitmid();
        
        checkbrnd();
        btnfalse();
        clr();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (bname.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Pleas enter brand name", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                db.iud("insert into brand(brand_id,bname)values('" + bid.getText() + "','" + bname.getText() + "')");
                JOptionPane.showMessageDialog(this, "Success");
                loadbnd();
                checkbrnd();

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        genbid();
        loadbnd();
        bname.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void upriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_upriceKeyTyped
        char c = evt.getKeyChar();
        if (c >= '0' && c <= '9') {

        } else if (c == '.') {
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_upriceKeyTyped

    private void spriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spriceKeyTyped
        char c = evt.getKeyChar();
        if (c >= '0' && c <= '9') {

        } else if (c == '.') {
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_spriceKeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            ResultSet rs = db.search("select * from brand where bname='" + bnd.getSelectedItem() + "'");
                if (rs.next()) {
            db.iud("update item set name='"+iname.getText()+"',unit_price='"+uprice.getText()+"',sale_price='"+sprice.getText()+"',"
                    + "brand_brand_id='"+rs.getString("brand_id")+"' where item_id='"+iid.getText()+"'");
            JOptionPane.showMessageDialog(this, "Success");
                }
        } catch (Exception e) {
        e.printStackTrace();
        }
        tablload();
        genitmid();
       
        checkbrnd();
        loadbdg();
        btnfalse();
        clr();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       if(sta.getText().equals("1")){
       JOptionPane.showMessageDialog(this,"Already activated");
       }else{
        try {
            db.iud("update item set status='1' where item_id='"+iid.getText()+"'");
        } catch (Exception e) {
        e.printStackTrace();
        }
       }
        
        loadbdg(); 
        tablload();
        genitmid();
       
        checkbrnd();
        btnfalse();
        clr();
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         if(sta.getText().equals("0")){
       JOptionPane.showMessageDialog(this,"Already deactivated");
       }else{
        try {
            db.iud("update item set status='0' where item_id='"+iid.getText()+"'");
        } catch (Exception e) {
        e.printStackTrace();
        }
       }
        loadbdg();
        tablload();
        genitmid();
  
        checkbrnd();
        btnfalse();
        clr();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        avbt.setEnabled(false);
        nme.setEditable(true);
        jButton7.setEnabled(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       int av=0;
        if(nme.getText().length()==0){
        JOptionPane.showMessageDialog(this, "Add type name please","Warning",JOptionPane.WARNING_MESSAGE);
        }else{
        try {
            ResultSet  rs=db.search("select tname from type");
            while(rs.next()){
            if(nme.getText().equalsIgnoreCase(rs.getString("tname"))){
            av=1;
            }
            }if(av==1){
                 JOptionPane.showMessageDialog(this, "Already avaibale this type","Warning",JOptionPane.WARNING_MESSAGE);
       
            }else{
            db.iud("insert into type(tname) values('"+nme.getText()+"')");
            }
        } catch (Exception e) {
        e.printStackTrace();
        }
        
        loadtp();
        avbt.setEnabled(true);
        nme.setEditable(false);
        jButton7.setEnabled(false);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
         avbt.setEnabled(false);
        nme.setEditable(true);
        jButton7.setEnabled(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void inameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inameActionPerformed
        uprice.grabFocus();
    }//GEN-LAST:event_inameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> avbt;
    private javax.swing.JLabel bdg;
    private javax.swing.JLabel bid;
    private javax.swing.JTextField bname;
    private javax.swing.JComboBox bnd;
    private javax.swing.JLabel iid;
    private javax.swing.JTextField iname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nme;
    private javax.swing.JTextField sprice;
    private javax.swing.JLabel st;
    private javax.swing.JLabel sta;
    private javax.swing.JTextField uprice;
    // End of variables declaration//GEN-END:variables

    private void clearall() {
        iid.setText(null);
        iname.setText(null);
        uprice.setText(null);
        sprice.setText(null);
    }

    private void sve() {
        if (sprice.getText().length() == 0 || iname.getText().length() == 0 || uprice.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Must enter highlight details", "Error", JOptionPane.ERROR_MESSAGE);

        } else {

            try {

                String id = iid.getText();
                String name = iname.getText();
                String unitprice = uprice.getText();
                String saleprice = sprice.getText();
                double qt = 0;

                ResultSet rs = db.search("select * from brand where bname='" + bnd.getSelectedItem() + "'");
                if (rs.next()) {
                    db.iud("insert into badge values('" + bdg.getText() + "')");
                  ResultSet rsst = db.search("select idtype from type where tname='" + avbt.getSelectedItem() + "'");
                  if(rsst.next()){
                    db.iud("insert into item(item_id,name,add_date,unit_price,sale_price,status,brand_brand_id,badge_badge_number,type_idtype) values('" + id + "','" + name + "','" + Main.mdatee.getText() + "','" + unitprice + "','" + saleprice + "','1','" + rs.getString("brand_id") + "','" + bdg.getText() + "','"+rsst.getString("idtype")+"')");
                  JOptionPane.showMessageDialog(this, "Success");
                  }

                }
                db.iud("insert into stock(qty,item_item_id) values('" + qt + "','" + id + "')");
                DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
                dtm.setRowCount(0);
                tablload();
                genitmid();
               
                iname.setText(null);
                uprice.setText(null);
                sprice.setText(null);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    private void genitmid() {
        try {

            ResultSet rs = db.search("select count(item_id) as x from item");

            if (rs.next()) {
                //string ekak int kalannaa
                int x = Integer.parseInt(rs.getString("x"));
                x++;
                if (x < 10) {
                    iid.setText("ITM00" + x);
                } else if (x < 100) {
                    iid.setText("ITM0" + x);
                } else {
                    iid.setText("ITM" + x);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void tablload() {
        try {
            int q = 1;
            ResultSet rs = db.search("select a.*,b.* from (item a inner join brand b  on a.brand_brand_id=b.brand_id)");
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            while (rs.next()) {

                Vector v = new Vector();
                v.add(rs.getString("item_id"));
                v.add(rs.getString("name"));
                v.add(rs.getString("unit_price"));
                v.add(rs.getString("sale_price"));
                v.add(rs.getString("bname"));

                v.add(rs.getString("badge_badge_number"));
                v.add(rs.getString("status"));
                dtm.addRow(v);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

   
    

    private void genbid() {
        try {

            ResultSet rs = db.search("select count(brand_id) as x from brand");

            if (rs.next()) {
                //string ekak int kalannaa
                int x = Integer.parseInt(rs.getString("x"));
                x++;
                if (x < 10) {
                    bid.setText("BRD00" + x);
                } else if (x < 100) {
                    bid.setText("BRD0" + x);
                } else {
                    bid.setText("BRD" + x);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadbnd() {

        try {
            bnd.removeAllItems();
            ResultSet rs = db.search("select * from brand");
            while (rs.next()) {
                bnd.addItem(rs.getString("bname"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void checkbrnd() {
        try {

            ResultSet rs = db.search("select count(brand_id) as x from brand");

            if (rs.next()) {
                //string ekak int kalannaa
                int x = Integer.parseInt(rs.getString("x"));
                if (x == 0) {
                    jButton5.setEnabled(false);
                    JOptionPane.showMessageDialog(this, "Please add new brand");
                } else {
                    jButton5.setEnabled(true);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadbdg() {
        try {

            ResultSet rs = db.search("select count(badge_number) as x from badge");

            if (rs.next()) {
                //string ekak int kalannaa
                int x = Integer.parseInt(rs.getString("x"));
                x++;
                if (x < 10) {
                    bdg.setText("BDG00" + x);
                } else if (x < 100) {
                    bdg.setText("BDG0" + x);
                } else {
                    bdg.setText("BDG" + x);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void btnfalse() {
        jButton4.setEnabled(false);
        jButton3.setEnabled(false);
    jButton5.setEnabled(true);
        jButton2.setEnabled(false); 
    }
    

    private void btntrue() {
       jButton4.setEnabled(true);
        jButton3.setEnabled(true);
        jButton2.setEnabled(true);
    jButton5.setEnabled(false);
    }

    private void clr() {
       iname.setText(null);
        uprice.setText(null);
        sprice.setText(null);
        sta.setText(null);
    }

    private void loadtp() {
        try {
            avbt.removeAllItems();
            ResultSet rs=db.search("select * from type");
            while(rs.next()){
            avbt.addItem(rs.getString("tname"));
            }
        } catch (Exception e) {
        e.printStackTrace();
        }
   
    }
}
