/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodcity;

import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TED
 */
public class mainacc extends javax.swing.JPanel {

    /**
     * Creates new form mainacc
     */
    public mainacc() {
        initComponents();
        loadmny();
        loadmaintain();
        loadpetti();
        loadpo();
        loadtotexpence();
        profit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        potot = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        avp = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        totex = new javax.swing.JLabel();
        ptot = new javax.swing.JLabel();
        maintot = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        monthtt = new javax.swing.JTextField();
        pmonthtot = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        pomnthtot = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        y = new javax.swing.JTextField();
        m = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        y1 = new javax.swing.JTextField();
        m1 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        y2 = new javax.swing.JTextField();
        m2 = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        pdis = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lb = new javax.swing.JLabel();
        li = new javax.swing.JLabel();
        lg = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        lm = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        lp = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        ln = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Prototype", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MAIN  ACCOUNT");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 30));

        potot.setFont(new java.awt.Font("Prototype", 1, 25)); // NOI18N
        potot.setForeground(new java.awt.Color(255, 204, 204));
        jPanel1.add(potot, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 630, 240, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 204));
        jLabel3.setText(" Balance");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, 90, 30));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Value", "Loger"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 270, 250, 250));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 102));
        jLabel5.setText("Purchase Order Expences Until Now");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 610, 230, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 102));
        jLabel6.setText("Petti Cash Expences");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 170, 20));

        avp.setFont(new java.awt.Font("Prototype", 1, 50)); // NOI18N
        avp.setForeground(new java.awt.Color(204, 255, 204));
        jPanel1.add(avp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 370, 50));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 204));
        jLabel8.setText("AVAILABLE BALANCE");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 102));
        jLabel9.setText("Purchase Order Expences");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 190, 190, 20));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Value", "Loger"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 250, 250));

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Value", "Loger"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable5);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 250, 250));

        totex.setFont(new java.awt.Font("Prototype", 1, 50)); // NOI18N
        totex.setForeground(new java.awt.Color(255, 204, 204));
        jPanel1.add(totex, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 380, 50));

        ptot.setFont(new java.awt.Font("Prototype", 1, 25)); // NOI18N
        ptot.setForeground(new java.awt.Color(255, 204, 204));
        jPanel1.add(ptot, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 630, 240, 40));

        maintot.setFont(new java.awt.Font("Prototype", 1, 25)); // NOI18N
        maintot.setForeground(new java.awt.Color(255, 204, 204));
        jPanel1.add(maintot, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 630, 240, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 102));
        jLabel12.setText("Maintains Expences ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 170, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 51, 102));
        jLabel14.setText("Petti Cash Expences Until Now");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 610, 170, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 51, 102));
        jLabel15.setText("Maintains Expences  For Until  now");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, 230, 20));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 51, 102));
        jLabel17.setText("Total :");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 50, 30));

        monthtt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        monthtt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(monthtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, 200, 30));

        pmonthtot.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pmonthtot.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(pmonthtot, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, 200, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 51, 102));
        jLabel18.setText("Total :");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, 50, 30));

        pomnthtot.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pomnthtot.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(pomnthtot, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 530, 200, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 51, 102));
        jLabel19.setText("Total :");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 530, 50, 30));
        jPanel1.add(y, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 80, 30));

        m.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        jPanel1.add(m, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 90, 30));

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/srch.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 60, -1));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Month");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 50, 20));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Year");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 50, 20));

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Year");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 50, 20));
        jPanel1.add(y1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 80, 30));

        m1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        jPanel1.add(m1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 90, 30));

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Month");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 50, 20));

        jButton2.setBackground(new java.awt.Color(153, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/srch.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 60, 30));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Year");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 210, 50, 20));
        jPanel1.add(y2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, 80, 30));

        m2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        jPanel1.add(m2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 230, 90, 30));

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Month");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 210, 50, 20));

        jButton3.setBackground(new java.awt.Color(153, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/srch.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 230, 60, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 102));
        jLabel4.setText("TOTAL EXPENCES   FOR THIS YEAR");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 260, 20));

        pdis.setForeground(new java.awt.Color(255, 255, 255));
        pdis.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pdis.setText("0");
        jPanel1.add(pdis, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 70, 130, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" All Invoice Vlaue");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, 90, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("PO discount");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 70, 90, 20));

        lb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb.setForeground(new java.awt.Color(51, 255, 204));
        lb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb.setText(" 0");
        jPanel1.add(lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 90, 130, 30));

        li.setForeground(new java.awt.Color(255, 255, 255));
        li.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        li.setText("0");
        jPanel1.add(li, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, 120, 20));

        lg.setForeground(new java.awt.Color(255, 255, 255));
        lg.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lg.setText("0");
        jPanel1.add(lg, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 50, 130, 20));

        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255)));
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 50, 240, 20));

        jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255)));
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, 240, 30));

        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255)));
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 70, 240, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(" All Grn Value");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 50, 90, 20));

        jLabel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255)));
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, 240, 20));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText(" Maintain");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 120, 90, 20));

        lm.setForeground(new java.awt.Color(255, 255, 255));
        lm.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lm.setText("0");
        jPanel1.add(lm, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 120, 130, 20));

        jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255)));
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 120, 240, 20));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText(" Petti Cash");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 140, 90, 20));

        lp.setForeground(new java.awt.Color(255, 255, 255));
        lp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lp.setText("0");
        jPanel1.add(lp, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 140, 130, 20));

        jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255)));
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 140, 240, 20));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(51, 255, 204));
        jLabel34.setText(" Net Profit");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, 90, 30));

        ln.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ln.setForeground(new java.awt.Color(51, 255, 204));
        ln.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ln.setText("0");
        jPanel1.add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 160, 130, 30));

        jLabel36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255)));
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, 240, 30));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/Untitled-2.png"))); // NOI18N
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 60, 60));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/cncl.png"))); // NOI18N
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 70, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/bck.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 690));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 690));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       DefaultTableModel dtm = (DefaultTableModel) jTable5.getModel();
        dtm.setRowCount(0);
        int lol=0;
        if (y.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Please enter year", "Warning", JOptionPane.WARNING_MESSAGE);
            y.grabFocus();
        } else if (y.getText().length() != 4) {
            JOptionPane.showMessageDialog(this, "Please enter correct year", "Warning", JOptionPane.WARNING_MESSAGE);
            y.grabFocus();
        } else {
            String month = m.getSelectedItem().toString();
            String mn = "";
            if (month.equalsIgnoreCase("jan")) {
                mn = "01";
            } else if (month.equalsIgnoreCase("feb")) {
                mn = "02";
            } else if (month.equalsIgnoreCase("mar")) {
                mn = "03";
            } else if (month.equalsIgnoreCase("apr")) {
                mn = "04";
            } else if (month.equalsIgnoreCase("may")) {
                mn = "05";
            } else if (month.equalsIgnoreCase("jun")) {
                mn = "06";
            } else if (month.equalsIgnoreCase("jul")) {
                mn = "07";
            } else if (month.equalsIgnoreCase("aug")) {
                mn = "08";
            } else if (month.equalsIgnoreCase("sep")) {
                mn = "09";
            } else if (month.equalsIgnoreCase("oct")) {
                mn = "10";
            } else if (month.equalsIgnoreCase("nov")) {
                mn = "11";
            } else if (month.equalsIgnoreCase("dec")) {
                mn = "12";
            }
            String d = y.getText() + "-" + mn;
            try {
                double tt=0;
                ResultSet rs=db.search("select * from maintains where date like '%"+d+"%'");
            while(rs.next()){
                Vector v=new Vector();
                v.add(rs.getString("date"));
                 v.add(rs.getString("amount"));
                 tt=tt+Double.parseDouble(rs.getString("amount"));
                 ResultSet rss=db.search("select fname,lname from emp where emp_id='"+rs.getString("emp_emp_id")+"'");
                 if(rss.next()){
                 v.add(rss.getString("fname")+" "+rss.getString("lname"));
                 }
                 dtm.addRow(v);
                
            }
            monthtt.setText(""+tt);
            } catch (Exception e) {
            e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTable4.getModel();
        dtm.setRowCount(0);
        int lol=0;
        if (y1.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Please enter year", "Warning", JOptionPane.WARNING_MESSAGE);
            y1.grabFocus();
        } else if (y1.getText().length() != 4) {
            JOptionPane.showMessageDialog(this, "Please enter correct year", "Warning", JOptionPane.WARNING_MESSAGE);
            y1.grabFocus();
        } else {
            String month = m1.getSelectedItem().toString();
            String mn = "";
            if (month.equalsIgnoreCase("jan")) {
                mn = "01";
            } else if (month.equalsIgnoreCase("feb")) {
                mn = "02";
            } else if (month.equalsIgnoreCase("mar")) {
                mn = "03";
            } else if (month.equalsIgnoreCase("apr")) {
                mn = "04";
            } else if (month.equalsIgnoreCase("may")) {
                mn = "05";
            } else if (month.equalsIgnoreCase("jun")) {
                mn = "06";
            } else if (month.equalsIgnoreCase("jul")) {
                mn = "07";
            } else if (month.equalsIgnoreCase("aug")) {
                mn = "08";
            } else if (month.equalsIgnoreCase("sep")) {
                mn = "09";
            } else if (month.equalsIgnoreCase("oct")) {
                mn = "10";
            } else if (month.equalsIgnoreCase("nov")) {
                mn = "11";
            } else if (month.equalsIgnoreCase("dec")) {
                mn = "12";
            }
            String d = y1.getText() + "-" + mn;
            try {
                double tt=0;
                ResultSet rs=db.search("select * from petty_cash where date like '%"+d+"%'");
            while(rs.next()){
                Vector v=new Vector();
                v.add(rs.getString("date"));
                 v.add(rs.getString("amount"));
                 tt=tt+Double.parseDouble(rs.getString("amount"));
                 ResultSet rss=db.search("select fname,lname from emp where emp_id='"+rs.getString("emp_emp_id")+"'");
                 if(rss.next()){
                 v.add(rss.getString("fname")+" "+rss.getString("lname"));
                 }
                 dtm.addRow(v);
                
            }
            pmonthtot.setText(""+tt);
            } catch (Exception e) {
            e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        dtm.setRowCount(0);
        int lol=0;
        if (y2.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Please enter year", "Warning", JOptionPane.WARNING_MESSAGE);
            y2.grabFocus();
        } else if (y2.getText().length() != 4) {
            JOptionPane.showMessageDialog(this, "Please enter correct year", "Warning", JOptionPane.WARNING_MESSAGE);
            y2.grabFocus();
        } else {
            String month = m2.getSelectedItem().toString();
            String mn = "";
            if (month.equalsIgnoreCase("jan")) {
                mn = "01";
            } else if (month.equalsIgnoreCase("feb")) {
                mn = "02";
            } else if (month.equalsIgnoreCase("mar")) {
                mn = "03";
            } else if (month.equalsIgnoreCase("apr")) {
                mn = "04";
            } else if (month.equalsIgnoreCase("may")) {
                mn = "05";
            } else if (month.equalsIgnoreCase("jun")) {
                mn = "06";
            } else if (month.equalsIgnoreCase("jul")) {
                mn = "07";
            } else if (month.equalsIgnoreCase("aug")) {
                mn = "08";
            } else if (month.equalsIgnoreCase("sep")) {
                mn = "09";
            } else if (month.equalsIgnoreCase("oct")) {
                mn = "10";
            } else if (month.equalsIgnoreCase("nov")) {
                mn = "11";
            } else if (month.equalsIgnoreCase("dec")) {
                mn = "12";
            }
            String d = y2.getText() + "-" + mn;
            try {
                double tt=0;
                ResultSet rs=db.search("select * from grn where date like '%"+d+"%'");
            while(rs.next()){
                Vector v=new Vector();
                v.add(rs.getString("date"));
                 v.add(rs.getString("net_tot"));
                 tt=tt+Double.parseDouble(rs.getString("net_tot"));
                 ResultSet rss=db.search("select fname,lname from emp where emp_id='"+rs.getString("emp_emp_id")+"'");
                 if(rss.next()){
                 v.add(rss.getString("fname")+" "+rss.getString("lname"));
                 }
                 dtm.addRow(v);
                
            }
            pomnthtot.setText(""+tt);
            } catch (Exception e) {
            e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        loadmny();
        loadmaintain();
        loadpetti();
        loadpo();
        loadtotexpence();
        profit();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Main.mp.removeAll();
        Main.mp.revalidate();
        run r=new run();
        Main.mp.add(r);
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lg;
    private javax.swing.JLabel li;
    private javax.swing.JLabel lm;
    private javax.swing.JLabel ln;
    private javax.swing.JLabel lp;
    private javax.swing.JComboBox<String> m;
    private javax.swing.JComboBox<String> m1;
    private javax.swing.JComboBox<String> m2;
    private javax.swing.JLabel maintot;
    private javax.swing.JTextField monthtt;
    private javax.swing.JLabel pdis;
    private javax.swing.JTextField pmonthtot;
    private javax.swing.JTextField pomnthtot;
    private javax.swing.JLabel potot;
    private javax.swing.JLabel ptot;
    private javax.swing.JLabel totex;
    private javax.swing.JTextField y;
    private javax.swing.JTextField y1;
    private javax.swing.JTextField y2;
    // End of variables declaration//GEN-END:variables

    private void loadmny() {
        try {
            double m=0;
            ResultSet rs=db.search("select * from money_account");
            if(rs.next()){
               m= Double.parseDouble(rs.getString("amount"));
           
            }
              avp.setText(""+m);
            li.setText(""+m);       
        } catch (Exception e) {
        e.printStackTrace();
        }
}

    private void loadmaintain() {
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy");
        Date d=new Date();
        String dd=sdf.format(d);
        try {
            double tot=0;
            ResultSet rs=db.search("select * from maintains where date like '%"+dd+"%'");
            while(rs.next()){
            tot=tot+Double.parseDouble(rs.getString("amount"));
            }
            maintot.setText(""+tot);
             lm.setText(""+tot);
        } catch (Exception e) {
        e.printStackTrace();
        }
    
    }

    private void loadpetti() {
         SimpleDateFormat sdf=new SimpleDateFormat("yyyy");
        Date d=new Date();
        String dd=sdf.format(d);
        try {
            double tot=0;
            ResultSet rs=db.search("select * from petty_cash where date like '%"+dd+"%'");
            while(rs.next()){
            tot=tot+Double.parseDouble(rs.getString("amount"));
            }
            ptot.setText(""+tot);
             lp.setText(""+tot);
        } catch (Exception e) {
        e.printStackTrace();
        } }

    private void loadpo() {
      SimpleDateFormat sdf=new SimpleDateFormat("yyyy");
        Date d=new Date();
        String dd=sdf.format(d);
        try {
            double tot=0;
            ResultSet rs=db.search("select * from po_pay where status='1' and date like '%"+dd+"%'");
            while(rs.next()){
            tot=tot+Double.parseDouble(rs.getString("amount"));
            }
            ResultSet rs1=db.search("select * from item_has_grn");
            double tott=0;
            while(rs1.next()){
            tott=tott+Double.parseDouble(rs1.getString("subtot"));
                    
            }
            potot.setText(""+tot);
            lg.setText(""+tot);
            pdis.setText(""+tott);
        } catch (Exception e) {
        e.printStackTrace();
        }   
    }

    private void loadtotexpence() {
       double a=Double.parseDouble(maintot.getText());
        double b=Double.parseDouble(ptot.getText());
         double c=Double.parseDouble(potot.getText());
         double tt=a+b+c;
         totex.setText(""+tt);
    }

    private void profit() {
       double a=Double.parseDouble(li.getText());
        double b=Double.parseDouble(lg.getText());
        double l=a-b;
        lb.setText(""+l);
         double c=Double.parseDouble(lm.getText()); 
         double d=Double.parseDouble(lp.getText()); 
         double l1=(l-c)-d;
         double pd=Double.parseDouble(pdis.getText());
         l1=l1+pd;
         
         ln.setText(""+l1);
    }
}
