/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodcity;

import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TED
 */
public class maintview extends javax.swing.JPanel {

    /**
     * Creates new form maintview
     */
    public maintview() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ye = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        mo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        dis = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nt = new javax.swing.JLabel();
        mg = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(ye, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 200, 30));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Year :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 40, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Maintain id", "Date", "amount", "User"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 1020, 200));

        mo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apri", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        add(mo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 200, 30));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Month :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 60, 30));

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/srch.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 60, 30));

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/ok.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, 180, -1));

        dis.setColumns(20);
        dis.setRows(5);
        jScrollPane2.setViewportView(dis);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 1020, 80));

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("C H E C K   O L D   M A I N T A I N A N S    D E T A I L S");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 510, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 0));
        jLabel4.setText("Net Total :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 360, 80, 30));

        nt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nt.setForeground(new java.awt.Color(0, 255, 0));
        add(nt, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 360, 100, 30));

        mg.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mg.setForeground(new java.awt.Color(204, 0, 0));
        add(mg, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 590, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/ll.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 540));
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        dis.setText(null);
        int x=jTable1.getSelectedRow();
        String id=jTable1.getValueAt(x, 0).toString();
        try {
            ResultSet rs=db.search("select * from maintains where maintains_id='"+id+"'");
            if(rs.next()){
                dis.setText(rs.getString("description"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(ye.getText().length()==0){
            JOptionPane.showMessageDialog(this, "Please enter year","Error",JOptionPane.ERROR_MESSAGE);
            ye.grabFocus();
        }else if(ye.getText().length()<4){
            JOptionPane.showMessageDialog(this, "Please enter correct year","Error",JOptionPane.ERROR_MESSAGE);
            ye.grabFocus();
        }else{
            String xa = "0";
            String month=mo.getSelectedItem().toString();
       if(month.equals("Jan")){
       searchdate("01");
       }else if(month.equals("Feb")){
       searchdate("02");
       }else if(month.equals("Mar")){
       searchdate("03");
       }else if(month.equals("Apri")){
       searchdate("04");
       }else if(month.equals("May")){
       searchdate("05");
       }else if(month.equals("Jun")){
       searchdate("06");
       }else if(month.equals("Jul")){
       searchdate("07");
       }else if(month.equals("Aug")){
       searchdate("08");
       }else if(month.equals("Sep")){
       searchdate("09");
       }else if(month.equals("Oct")){
       searchdate("10");
       }else if(month.equals("Nov")){
       searchdate("11");
       }else if(month.equals("Dec")){
       searchdate("12");
       }

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
        dtm.setRowCount(0);
        dis.setText(null);
        ye.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea dis;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel mg;
    private javax.swing.JComboBox<String> mo;
    private javax.swing.JLabel nt;
    private javax.swing.JTextField ye;
    // End of variables declaration//GEN-END:variables

    private void searchdate(String da) {
        int lola = 0;
        Date d = new Date();
       

        try {
            ResultSet rs = db.search("select * from maintains where date like '" + ye.getText() + "%'");
            if (rs.next()) {
                String dat = ye.getText() + "-" + da;
                 ResultSet rs1 = db.search("select * from maintains where date like '" + dat + "%'");
                while (rs1.next()) {
                    lola = 1;
                    mg.setText(null);
                    DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
                    Vector v = new Vector();
                    v.add(rs1.getString("maintains_id"));
                    v.add(rs1.getString("date"));
                    v.add(rs1.getString("amount"));
                   ResultSet rs3=db.search("select fname from emp where emp_id='"+rs1.getString("emp_emp_id")+"'");
                   if(rs3.next()){
                   v.add(rs3.getString("fname"));
                    }
                   
                   dtm.addRow(v); 
                    
                }
                if (lola == 0) {
                    DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
                    dtm.setRowCount(0);
                    mg.setText("NO data you selected month. Please check another month. Thank you.");
                
                    
                } else {
                    
                }
                lola = 0;
                
               
            } else {
               JOptionPane.showMessageDialog(this, "NO data you selected month. Please check another month. Thank you.","Error",JOptionPane.ERROR_MESSAGE);
              dis.setText(null);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        double amm=0;
         for (int i = 0; i < jTable1.getRowCount(); i++) {
             
                     amm=amm+Double.parseDouble(jTable1.getValueAt(i, 2).toString());
                }
                nt.setText(""+amm);
        }
}
