/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodcity;

import java.sql.ResultSet;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author TED
 */
public class maintainancenew extends javax.swing.JPanel {

    /**
     * Creates new form maintainancenew
     */
    public maintainancenew() {
        initComponents();
        genid();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        am = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dis = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        mid = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("N E W   M A I N T A I N A N S E");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 490, 20));
        add(am, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 190, 30));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Maintainance ID :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 120, 30));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Amount :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 70, 30));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Description :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 90, 30));

        dis.setColumns(20);
        dis.setRows(5);
        jScrollPane1.setViewportView(dis);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 910, 280));

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/esv.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 140, 40));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/ecan.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, 140, 40));
        add(mid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 180, 30));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/ll.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 540));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (am.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "please add amount", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (dis.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "please add disscription", "Error", JOptionPane.ERROR_MESSAGE);
        } else {

            try {
                Date da = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String dt = sdf.format(da);
                String name = "";
                ResultSet rs = db.search("select emp_emp_id from login where user_name='" + Main.muser.getText() + "'");
                if (rs.next()) {
                    name = rs.getString("emp_emp_id");

                    ResultSet rs1 = db.search("select * from money_account");
                    if(rs1.next()) {
                        double avamount = Double.parseDouble(rs1.getString("amount"));
                        double needamount = Double.parseDouble(am.getText());
                        double newamount = avamount - needamount;
                        double lk=100000;
                        if (newamount > lk) {
                            
                                double amou = Double.parseDouble(am.getText());
                                db.iud("insert into maintains(maintains_id,date,description,emp_emp_id,amount) values('" + mid.getText() + "','" + dt + "','" + dis.getText() + "','" + name + "','" + amou + "')");

                                db.iud("update money_account set amount='" + newamount + "'");
                                JOptionPane.showMessageDialog(this, "Success");
                           } else {
                            System.out.println("loli");
                            JOptionPane.showMessageDialog(this, "You can't do this maintain you havent money", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        System.out.println("ppp");
                         JOptionPane.showMessageDialog(this, "You can't do this maintain you havent money", "Error", JOptionPane.ERROR_MESSAGE);
                        
                    }
                }
                genid();
                am.setText(null);
                dis.setText(null);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        genid();
        am.setText(null);
        dis.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField am;
    private javax.swing.JTextArea dis;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mid;
    // End of variables declaration//GEN-END:variables

    private void genid() {
        try {
            ResultSet rs = db.search("select count(maintains_id) as x from maintains");
            if (rs.next()) {
                int x = Integer.parseInt(rs.getString("x"));
                x++;
                if (x < 10) {
                    mid.setText("M00" + x);
                } else if (x < 100) {
                    mid.setText("M0" + x);
                } else {
                    mid.setText("M" + x);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
