/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodcity;

import java.sql.ResultSet;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author TED
 */
public class pettycashadd extends javax.swing.JPanel {

    /**
     * Creates new form pettycashadd
     */
    public pettycashadd() {
        initComponents();
        genid();
        loadamount();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pid = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        am = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        dis = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        avam = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("A D D    N E W    P E T T Y   C A S H");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 490, 20));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Petty cash id :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 90, 30));
        add(pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 210, 30));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Description :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 90, 30));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Amount :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 70, 30));
        add(am, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 230, 30));

        dis.setColumns(20);
        dis.setRows(5);
        jScrollPane1.setViewportView(dis);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 910, 280));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/ecan.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 140, 40));

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/esv.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, 140, 40));

        avam.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        avam.setForeground(new java.awt.Color(255, 255, 255));
        avam.setText("0000000000");
        add(avam, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 410, 80));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Available  Petty Cash Amount For This Month");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 280, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/ll.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 540));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        genid();
        am.setText(null);
        dis.setText(null);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        double amo=0;
        double avb=0;
        if (am.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "please add amount", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (dis.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "please add disscription", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(Double.parseDouble(am.getText())>Double.parseDouble(avam.getText())){
           JOptionPane.showMessageDialog(this, "You dont have enough money sorry!!!", "Error", JOptionPane.ERROR_MESSAGE);
         
        }else {

            try {
                Date da = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("MM");
                SimpleDateFormat sdf2 = new SimpleDateFormat("yyyy");
                String dt = sdf.format(da);
                String month = "";
                if (dt.equalsIgnoreCase("01")) {
                    month = "January";
                } else if (dt.equalsIgnoreCase("02")) {
                    month = "February";
                } else if (dt.equalsIgnoreCase("03")) {
                    month = "March";
                } else if (dt.equalsIgnoreCase("04")) {
                    month = "April";
                } else if (dt.equalsIgnoreCase("05")) {
                    month = "May";
                } else if (dt.equalsIgnoreCase("06")) {
                    month = "June";
                } else if (dt.equalsIgnoreCase("07")) {
                    month = "July";
                } else if (dt.equalsIgnoreCase("08")) {
                    month = "August";
                } else if (dt.equalsIgnoreCase("09")) {
                    month = "September";
                } else if (dt.equalsIgnoreCase("10")) {
                    month = "Octomber";
                } else if (dt.equalsIgnoreCase("11")) {
                    month = "November";
                } else {
                    month = "December";
                }
                double ama = 0;
                SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM");
                String da2 = sdf1.format(da);
                ResultSet rs = db.search("select * from petty_cash_account where date like '" + da2 + "%'");
                if (rs.next()) {
                    
                        double avbbal = Double.parseDouble(rs.getString("amount"));
                        ama = Double.parseDouble(this.am.getText());
                        double netamount = avbbal - ama;
                        db.iud("update petty_cash_account set amount='" + netamount + "' where date='"+rs.getString("date")+"'");
                       
                    }
                
                ResultSet rs1=db.search("select * from login where user_name='"+Main.muser.getText()+"'");
                String eid="";
                if(rs1.next()){
                eid=rs1.getString("emp_emp_id");
                }
                db.iud("insert into petty_cash(petti_id,date,time,discription,emp_emp_id,amount)"
                        + "values('" + pid.getText() + "','" + Main.mdatee.getText() + "','" + new Timestamp(System.currentTimeMillis()) + "','" + dis.getText() + "','" +eid+ "','" + am.getText() + "') ");
                JOptionPane.showMessageDialog(this, "Success");

                genid();
                am.setText(null);
                dis.setText(null);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        loadamount();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField am;
    private javax.swing.JLabel avam;
    private javax.swing.JTextArea dis;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pid;
    // End of variables declaration//GEN-END:variables

    private void genid() {
        try {
            ResultSet rs = db.search("select count(petti_id) as x from petty_cash");
            if (rs.next()) {
                int x = Integer.parseInt(rs.getString("x"));
                x++;
                if (x < 10) {
                    pid.setText("PETTY00" + x);
                } else if (x < 100) {
                    pid.setText("PETTY0" + x);
                } else {
                    pid.setText("PETTY" + x);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadamount() {
        try {
            Date d=new Date();
            SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM");
            String dt=sdf.format(d);
            ResultSet rs=db.search("select * from petty_cash_account where date  like '%"+dt+"%'");
            if(rs.next()){
            avam.setText(rs.getString("amount"));
            }
        } catch (Exception e) {
        e.printStackTrace();
        }
}
}
