/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodcity;

import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class pettycheck extends javax.swing.JPanel {

    public pettycheck() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        dis = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ye = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        nt = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mg = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("C H E C K   O L D   P E T T Y   C A S H");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 370, 20));

        mo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apri", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        add(mo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 200, 30));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Year :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 40, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Petty cash id", "Date", "Time", "amount", "User"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 1020, 200));

        dis.setColumns(20);
        dis.setRows(5);
        jScrollPane2.setViewportView(dis);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 1020, 100));

        jButton1.setBackground(new java.awt.Color(51, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/ok.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, 180, 50));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Month :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 60, 30));
        add(ye, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 200, 30));

        jButton2.setBackground(new java.awt.Color(51, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/srch.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 60, -1));

        nt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        add(nt, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 360, 190, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Net total :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 360, 70, 30));

        mg.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mg.setForeground(new java.awt.Color(204, 0, 0));
        add(mg, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 590, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/ll.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 540));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        int lol = 0;
        if (ye.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Please enter year", "Warning", JOptionPane.WARNING_MESSAGE);
            ye.grabFocus();
        } else if (ye.getText().length() != 4) {
            JOptionPane.showMessageDialog(this, "Please enter correct year", "Warning", JOptionPane.WARNING_MESSAGE);
            ye.grabFocus();
        } else {
            String month = mo.getSelectedItem().toString();
            String mn = "";
            if (month.equalsIgnoreCase("jan")) {
                mn = "01";
            } else if (month.equalsIgnoreCase("feb")) {
                mn = "02";
            } else if (month.equalsIgnoreCase("mar")) {
                mn = "03";
            } else if (month.equalsIgnoreCase("apr")) {
                mn = "04";
            } else if (month.equalsIgnoreCase("may")) {
                mn = "05";
            } else if (month.equalsIgnoreCase("jun")) {
                mn = "06";
            } else if (month.equalsIgnoreCase("jul")) {
                mn = "07";
            } else if (month.equalsIgnoreCase("aug")) {
                mn = "08";
            } else if (month.equalsIgnoreCase("sep")) {
                mn = "09";
            } else if (month.equalsIgnoreCase("oct")) {
                mn = "10";
            } else if (month.equalsIgnoreCase("nov")) {
                mn = "11";
            } else if (month.equalsIgnoreCase("dec")) {
                mn = "12";
            }
            String d = ye.getText() + "-" + mn;
            try {
                ResultSet rs = db.search("select * from petty_cash where date like '%" + d + "%'");

                while (rs.next()) {
                    lol = 1;
                    mg.setText(null);
                    Vector v = new Vector();
                    v.add(rs.getString("petti_id"));
                    v.add(rs.getString("date"));
                    v.add(rs.getString("time"));
                    v.add(rs.getString("amount"));
                    ResultSet rs1 = db.search("select fname from emp where emp_id='" + rs.getString("emp_emp_id") + "' ");
                    if (rs1.next()) {
                        v.add(rs1.getString("fname"));
                        dtm.addRow(v);
                    }
                }
                if (lol == 0) {
                    DefaultTableModel dtm1 = (DefaultTableModel) jTable1.getModel();
                    dtm1.setRowCount(0);
                    mg.setText("NO data you selected month. Please check another month. Thank you.");
                    dis.setText(null);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            double amm = 0;
            for (int i = 0; i < jTable1.getRowCount(); i++) {

                amm = amm + Double.parseDouble(jTable1.getValueAt(i, 3).toString());
            }
            nt.setText("" + amm);

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        dis.setText(null);
        int x = jTable1.getSelectedRow();
        String id = jTable1.getValueAt(x, 0).toString();
        try {
            ResultSet rs = db.search("select * from petty_cash where petti_id='" + id + "'");
            if (rs.next()) {
                dis.setText(rs.getString("discription"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        dis.setText(null);
        ye.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea dis;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel mg;
    private javax.swing.JComboBox<String> mo;
    private javax.swing.JLabel nt;
    private javax.swing.JTextField ye;
    // End of variables declaration//GEN-END:variables
}
