/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodcity;

import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Senura
 */
public class poadd extends javax.swing.JPanel {

    int tblclock;
    String  sapa;
    public poadd() {
        initComponents();
        tblclock = 0;
        sapa="";
        genid();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        qty = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        des = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cn = new javax.swing.JTextField();
        iid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pid = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cnlist = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        iidlist = new javax.swing.JList();
        jLabel16 = new javax.swing.JLabel();
        tota = new javax.swing.JLabel();
        tt = new javax.swing.JLabel();
        up = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        nd = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("N E W   P U R C H A S E   O R D E R");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 490, 20));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/cltb.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 380, 160, 40));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/rm.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 310, 160, 40));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/ed.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 230, 160, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Id", "Description", "Unit Price", "Qty", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 820, 190));

        jButton6.setBackground(new java.awt.Color(0, 0, 51));
        jButton6.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(51, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/addtv.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 170, 90, 50));

        jLabel10.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total :");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, 70, 30));

        jLabel2.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Unit Price :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, 80, 30));

        jLabel9.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Qty :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 110, 30));

        qty.setBackground(new java.awt.Color(204, 204, 204));
        qty.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyActionPerformed(evt);
            }
        });
        qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qtyKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qtyKeyTyped(evt);
            }
        });
        add(qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 140, 30));

        jLabel5.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Description :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 100, 30));

        des.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        add(des, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 140, 30));

        jLabel8.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Supplier :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 80, 30));

        cn.setBackground(new java.awt.Color(204, 204, 204));
        cn.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        cn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cnKeyReleased(evt);
            }
        });
        add(cn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 110, 30));

        iid.setEditable(false);
        iid.setBackground(new java.awt.Color(204, 204, 204));
        iid.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        iid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                iidKeyReleased(evt);
            }
        });
        add(iid, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 140, 30));

        jLabel4.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Item ID :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 70, 30));

        jLabel3.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Po ID :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, 30));

        pid.setFont(new java.awt.Font("Prototype", 0, 14)); // NOI18N
        add(pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 220, 30));

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        cnlist.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        cnlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cnlistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(cnlist);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 110, 100));

        iidlist.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        iidlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iidlistMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(iidlist);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 110, 100));

        jLabel16.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Total :");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 430, 60, 30));

        tota.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        tota.setForeground(new java.awt.Color(204, 204, 204));
        add(tota, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, 180, 30));

        tt.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        add(tt, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 140, 120, 30));

        up.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        add(up, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 100, 120, 30));

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/ecan.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 470, 140, 40));

        jButton5.setForeground(new java.awt.Color(51, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/esv.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 470, 140, 40));
        add(nd, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 180, 30));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Need date ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 60, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/ll.png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 540));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int x = jTable1.getRowCount();
        if (x == 0) {
            JOptionPane.showMessageDialog(this, "No data in table", "Warning", JOptionPane.ERROR_MESSAGE);

        } else {
            lblclr();
            tblclear();

        }
        tota.setText("" + 0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (tblclock == 1) {
            //lblclr();
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            int x = jTable1.getSelectedRow();
            dtm.removeRow(x);

        } else {
            JOptionPane.showMessageDialog(this, "Please select colum from table", "Warning", JOptionPane.ERROR_MESSAGE);
        }
        tblclock = 0;
        tota();
        // j
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        lblclr();

        if (tblclock == 1) {

            int x = jTable1.getSelectedRow();
            iid.setText(jTable1.getValueAt(x, 0).toString());
            des.setText(jTable1.getValueAt(x, 1).toString());
            up.setText(jTable1.getValueAt(x, 2).toString());
            qty.setText(jTable1.getValueAt(x, 3).toString());
            tt.setText(jTable1.getValueAt(x, 4).toString());

            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.removeRow(x);

        } else {
            JOptionPane.showMessageDialog(this, "Please select colum from table", "Warning", JOptionPane.ERROR_MESSAGE);
        }
        tota();
        tblclock = 0;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        tblclock = 1;
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int x = jTable1.getRowCount();
        int y = 0;
        if (x == 0) {
            addTable();
        } else {
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

            for (int i = 0; i < jTable1.getRowCount(); i++) {

                String id = jTable1.getValueAt(i, 0).toString();
                if (id.equals(iid.getText())) {
                    y = 1;
                    double qt = Double.parseDouble(jTable1.getValueAt(i, 3).toString());
                    double addqty = Double.parseDouble(qty.getText());
                    double t = qt + addqty;
                    double upr = Double.parseDouble(up.getText());
                    double np = t * upr;
                    dtm.setValueAt(t, i, 3);
                    dtm.setValueAt(np, i, 4);
                }
            }
            if (y == 0) {

                Vector v = new Vector();
                v.add(iid.getText());
                v.add(des.getText());
                v.add(up.getText());
                v.add(qty.getText());
                v.add(tt.getText());
                dtm.addRow(v);

            }
        }
        tota();
        lblclr();

    }//GEN-LAST:event_jButton6ActionPerformed

    private void qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyActionPerformed

    }//GEN-LAST:event_qtyActionPerformed

    private void qtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyKeyReleased
        double upr = 0;
        double qt = 0;
        double st = 0;

        if (qty.getText().length() == 0) {
            if (up.getText().length() == 0) {

            } else {
                st = upr * qt;
                tt.setText("" + st);
            }
        } else {
            if (up.getText().length() == 0) {

            } else {
                upr = Double.parseDouble(up.getText());
                qt = Double.parseDouble(qty.getText());
                st = upr * qt;
                tt.setText("" + st);
            }
        }
    }//GEN-LAST:event_qtyKeyReleased

    private void qtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyKeyTyped
        char c = evt.getKeyChar();
        if (c >= '0' && c <= '9') {

        } else {
            evt.consume();
        }
    }//GEN-LAST:event_qtyKeyTyped

    private void cnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnKeyReleased
        try {
            ResultSet rs = db.search("select name from supplier where name like '%" + cn.getText() + "%' and status='1'");
            Vector v = new Vector();
            while (rs.next()) {
                cnlist.setVisible(true);
                v.add(rs.getString("name"));

            }
            cnlist.setListData(v);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cnKeyReleased

    private void cnlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cnlistMouseClicked

        cn.setText(cnlist.getSelectedValue().toString());
        cnlist.setVisible(false);
        try {
            ResultSet rs1 = db.search("select sup_id from supplier where name='" + cn.getText() + "'");
            if (rs1.next()) {
                sapa=rs1.getString("sup_id");
                ResultSet rs = db.search("select item_item_id from item_has_supplier where supplier_sup_id like '%" + rs1.getString("sup_id") + "%' ");
                Vector v = new Vector();
                while (rs.next()) {
                    iidlist.setVisible(true);
                    
                    v.add(rs.getString("item_item_id"));

                }
                iidlist.setListData(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cnlistMouseClicked

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked

    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        lblclr();
        tblclear();
        tota.setText("" + 0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (nd.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Please select need date", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            int x = jTable1.getRowCount();
            Date d = nd.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String dat = sdf.format(d);
            if (x == 0) {
                JOptionPane.showMessageDialog(this, "No data in table", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                try {
                    ResultSet rs = db.search("select emp_emp_id from login where user_name='" + Main.muser.getText() + "'");
                    String id = "";
                    if (rs.next()) {
                        id = rs.getString("emp_emp_id");
                        ResultSet rsk=db.search("select * from money_account");
                        if(rsk.next()){
                        double tk=Double.parseDouble(rsk.getString("amount"));
                        
                        double t = Double.parseDouble(tota.getText());
                        
                        double ntt=tk-t;
                            System.out.println(ntt);
                        if(ntt>500000){
                        db.iud("insert into purchase_order(po_id,date,need_date,emp_emp_id,total,supplier_sup_id,status) values ('" + pid.getText() + "','" + Main.mdatee.getText() + "','" + dat + "','" + id + "','" + t + "','"+sapa+"','1')");
                        for (int i = 0; i < jTable1.getRowCount(); i++) {
                            db.iud("insert into purchase_order_has_item(purchase_order_po_id,item_item_id,qty,tot)"
                                    + " values('" + pid.getText() + "','" + jTable1.getValueAt(i, 0).toString() + "','" + jTable1.getValueAt(i, 3).toString() + "','" + jTable1.getValueAt(i, 4).toString() + "')");
                        }
                        db.iud("insert into po_pay(purchase_order_po_id,status,amount) values('"+pid.getText()+"','0','"+t+"')");
                        
                        JOptionPane.showMessageDialog(this, "Success");

                        lblclr();
                        tblclear();

                        tota.setText("" + 0);
                        }else{
                        JOptionPane.showMessageDialog(this, "You cant do this. You haven't enough money");
                        }
                        }
                    }

                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void iidlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iidlistMouseClicked

        iid.setText(iidlist.getSelectedValue().toString());

        itmload();
    }//GEN-LAST:event_iidlistMouseClicked

    private void iidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_iidKeyReleased

    }//GEN-LAST:event_iidKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cn;
    private javax.swing.JList cnlist;
    private javax.swing.JLabel des;
    private javax.swing.JTextField iid;
    private javax.swing.JList iidlist;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JDateChooser nd;
    private javax.swing.JLabel pid;
    private javax.swing.JTextField qty;
    private javax.swing.JLabel tota;
    private javax.swing.JLabel tt;
    private javax.swing.JLabel up;
    // End of variables declaration//GEN-END:variables

    private void lblclr() {
        iid.setText(null);
        des.setText(null);
        qty.setText(null);
        up.setText(null);
        tt.setText(null);
    }

    private void addTable() {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        Vector v = new Vector();
        v.add(iid.getText());
        v.add(des.getText());
        v.add(up.getText());
        v.add(qty.getText());
        v.add(tt.getText());
        dtm.addRow(v);

        for (int i = 0; i < jTable1.getRowCount(); i++) {
            double nttot = Double.parseDouble(jTable1.getValueAt(i, 4).toString());
            tota.setText("" + nttot);
        }
        genid();

    }

    private void tblclear() {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
    }

    private void itmload() {
        try {
            ResultSet rs = db.search("select * from item where item_id like'%" + iid.getText() + "%'");
            if (rs.next()) {
                des.setText(rs.getString("name"));
                up.setText(rs.getString("unit_price"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        genid();
    }

    private void genid() {
        try {
            ResultSet rs = db.search("select count(po_id) as x from purchase_order");
            if (rs.next()) {
                int x = Integer.parseInt(rs.getString("x"));
                x++;
                if (x < 10) {
                    pid.setText("PO00" + x);
                } else if (x < 100) {
                    pid.setText("PO0" + x);
                } else {
                    pid.setText("PO" + x);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void tota() {
        double nttot=0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            nttot = nttot+Double.parseDouble(jTable1.getValueAt(i, 4).toString());
            
        }
        tota.setText("" + nttot);
    }
}
