/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodcity;

import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Gagan
 */
public class reports extends javax.swing.JPanel {

    /**
     * Creates new form reports
     */
    public reports() {
        initComponents();
        loadtype();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        c2 = new javax.swing.JRadioButton();
        c = new javax.swing.JRadioButton();
        c1 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        a2 = new javax.swing.JRadioButton();
        a = new javax.swing.JRadioButton();
        a1 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        b2 = new javax.swing.JRadioButton();
        b = new javax.swing.JRadioButton();
        b1 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        d2 = new javax.swing.JRadioButton();
        d = new javax.swing.JRadioButton();
        d1 = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        e1 = new javax.swing.JRadioButton();
        jButton5 = new javax.swing.JButton();
        e2 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        y = new javax.swing.JTextField();
        m = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ye = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Prototype", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" REPORTS OF FOOD CITY");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 30));

        buttonGroup1.add(c2);
        c2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        c2.setForeground(new java.awt.Color(255, 204, 204));
        c2.setText("Not  Working  Employee Only");
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, -1, -1));

        buttonGroup1.add(c);
        c.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        c.setForeground(new java.awt.Color(255, 204, 204));
        c.setSelected(true);
        c.setText("All Employee");
        add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, -1, -1));

        buttonGroup1.add(c1);
        c1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        c1.setForeground(new java.awt.Color(255, 204, 204));
        c1.setText("Working  Employee Only");
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText(" GET REPORT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 200, 110, -1));

        buttonGroup2.add(a2);
        a2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        a2.setForeground(new java.awt.Color(255, 204, 204));
        a2.setText("Not Available Supplier");
        a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2ActionPerformed(evt);
            }
        });
        add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        buttonGroup2.add(a);
        a.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        a.setForeground(new java.awt.Color(255, 204, 204));
        a.setSelected(true);
        a.setText("All Supplier");
        add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        buttonGroup2.add(a1);
        a1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        a1.setForeground(new java.awt.Color(255, 204, 204));
        a1.setText("Available Supplier");
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });
        add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText(" GET REPORT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 110, -1));

        buttonGroup3.add(b2);
        b2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b2.setForeground(new java.awt.Color(255, 204, 204));
        b2.setText("Not Available Item");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, -1, -1));

        buttonGroup3.add(b);
        b.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b.setForeground(new java.awt.Color(255, 204, 204));
        b.setSelected(true);
        b.setText("All Item");
        add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        buttonGroup3.add(b1);
        b1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b1.setForeground(new java.awt.Color(255, 204, 204));
        b1.setText("Available Item");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 204, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText(" GET REPORT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 110, -1));

        buttonGroup4.add(d2);
        d2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        d2.setForeground(new java.awt.Color(255, 204, 204));
        d2.setText("Not Available Banks");
        d2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d2ActionPerformed(evt);
            }
        });
        add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, -1, -1));

        buttonGroup4.add(d);
        d.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        d.setForeground(new java.awt.Color(255, 204, 204));
        d.setSelected(true);
        d.setText(" All  Banks");
        add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, -1, -1));

        buttonGroup4.add(d1);
        d1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        d1.setForeground(new java.awt.Color(255, 204, 204));
        d1.setText("Available Banks");
        d1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d1ActionPerformed(evt);
            }
        });
        add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, -1, -1));

        jButton4.setBackground(new java.awt.Color(0, 204, 204));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText(" GET REPORT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, 110, -1));

        buttonGroup5.add(e1);
        e1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        e1.setForeground(new java.awt.Color(255, 204, 204));
        e1.setSelected(true);
        e1.setText("Available Stock");
        add(e1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 530, -1, -1));

        jButton5.setBackground(new java.awt.Color(0, 204, 204));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText(" GET REPORT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 610, 110, -1));

        buttonGroup5.add(e2);
        e2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        e2.setForeground(new java.awt.Color(255, 204, 204));
        e2.setText("Type selecting");
        e2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e2ActionPerformed(evt);
            }
        });
        add(e2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 570, -1, -1));

        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 570, 180, 20));

        jLabel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Stock  Reports", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(204, 255, 204))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, 350, 160));

        jButton6.setBackground(new java.awt.Color(0, 204, 204));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setText(" GET REPORT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 610, 110, -1));

        y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yActionPerformed(evt);
            }
        });
        add(y, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 1110, 150, 30));

        m.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        add(m, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 550, 130, 30));

        jLabel8.setForeground(new java.awt.Color(204, 255, 255));
        jLabel8.setText("Month");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, -1, -1));

        jLabel9.setForeground(new java.awt.Color(204, 255, 255));
        jLabel9.setText("Year");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, -1, -1));

        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Item Reports", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(204, 255, 204))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 350, 160));

        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee  Reports", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(204, 255, 204))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 350, 160));

        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Supplier  Reports", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(204, 255, 204))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 350, 160));

        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bank  Reports", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(204, 255, 204))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 350, 160));

        ye.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                yeKeyTyped(evt);
            }
        });
        add(ye, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, 140, 30));

        jLabel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Salary  Reports", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(204, 255, 204))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 350, 160));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/cncl.png"))); // NOI18N
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 580, 70, 60));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/bck.png"))); // NOI18N
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1020, 640));
    }// </editor-fold>//GEN-END:initComponents

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c2ActionPerformed

    private void a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a2ActionPerformed

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void d2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d2ActionPerformed

    private void d1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String path = "";
        if (a.isSelected()) {
            path = "C:\\ProgramData\\supercity\\2\\allsupplier.jrxml";
        } else if (a1.isSelected()) {
            try {
                path = "C:\\ProgramData\\supercity\\2\\avsup.jrxml";

            } catch (Exception e) {
                e.printStackTrace();
            }
        } else if (a2.isSelected()) {
            try {
                path = "C:\\ProgramData\\supercity\\2\\notavsup.jrxml";

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        try {
            JasperReport jr = JasperCompileManager.compileReport(path);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, db.con());
            JasperViewer.viewReport(jp, false);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String path = "";
        if (b.isSelected()) {
            path = "C:\\ProgramData\\supercity\\2\\itemall.jrxml";
        } else if (b1.isSelected()) {
            path = "C:\\ProgramData\\supercity\\2\\itemav.jrxml";
        } else if (b2.isSelected()) {
            path = "C:\\ProgramData\\supercity\\2\\itemnoav.jrxml";
        }
        try {
            JasperReport jr = JasperCompileManager.compileReport(path);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, db.con());
            JasperViewer.viewReport(jp, false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String path = "";
        if (c.isSelected()) {
            path = "C:\\ProgramData\\supercity\\2\\empall.jrxml";
        } else if (c1.isSelected()) {
            path = "C:\\ProgramData\\supercity\\2\\empav.jrxml";
        } else if (c2.isSelected()) {
            path = "C:\\ProgramData\\supercity\\2\\empnoav.jrxml";
        }
        try {
            JasperReport jr = JasperCompileManager.compileReport(path);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, db.con());
            JasperViewer.viewReport(jp, false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String path = "";
        if (d.isSelected()) {
            path = "C:\\ProgramData\\supercity\\2\\bankall.jrxml";
        } else if (d1.isSelected()) {
            path = "C:\\ProgramData\\supercity\\2\\bankav.jrxml";
        } else if (d2.isSelected()) {
            path = "C:\\ProgramData\\supercity\\2\\banknoav.jrxml";
        }
        try {
            JasperReport jr = JasperCompileManager.compileReport(path);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, db.con());
            JasperViewer.viewReport(jp, false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (e1.isSelected()) {
            try {
                String path = "C:\\ProgramData\\supercity\\2\\stock.jrxml";
                JasperReport jr = JasperCompileManager.compileReport(path);
                JasperPrint jp = JasperFillManager.fillReport(jr, null, db.con());
                JasperViewer.viewReport(jp, false);
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else if (e2.isSelected()) {
            String bd = jComboBox1.getSelectedItem().toString();
            try {
                String path = "C:\\ProgramData\\supercity\\2\\stockbrand.jrxml";
                JasperReport jr = JasperCompileManager.compileReport(path);
                Map m = new HashMap<String, Object>();
                m.put("bn", bd);
                JasperPrint jp = JasperFillManager.fillReport(jr, m, db.con());
                JasperViewer.viewReport(jp, false);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void e2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (ye.getText().length() == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter year", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
            ye.grabFocus();
        } else if (ye.getText().length() != 4) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter correct year", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
            ye.grabFocus();
        } else {
            String month = m.getSelectedItem().toString();
            String mn = "";
            String mnth = "";
            if (month.equalsIgnoreCase("jan")) {
                mn = "01";
                mnth = "January";
            } else if (month.equalsIgnoreCase("feb")) {
                mn = "02";
                mnth = "February";
            } else if (month.equalsIgnoreCase("mar")) {
                mn = "03";
                mnth = "March";
            } else if (month.equalsIgnoreCase("apr")) {
                mn = "04";
                mnth = "April";
            } else if (month.equalsIgnoreCase("may")) {
                mn = "05";
                mnth = "May";
            } else if (month.equalsIgnoreCase("jun")) {
                mn = "06";
                mnth = "June";
            } else if (month.equalsIgnoreCase("jul")) {
                mn = "07";
                mnth = "July";
            } else if (month.equalsIgnoreCase("aug")) {
                mn = "08";
                mnth = "Augest";
            } else if (month.equalsIgnoreCase("sep")) {
                mn = "09";
                mnth = "September";
            } else if (month.equalsIgnoreCase("oct")) {
                mn = "10";
                mnth = "Octomber";
            } else if (month.equalsIgnoreCase("nov")) {
                mn = "11";
                mnth = "November";
            } else if (month.equalsIgnoreCase("dec")) {
                mn = "12";
                mnth = "December";
            }
          
            String d = ye.getText() + "-" + mn;
             System.out.println(d);
            try {
                ResultSet rs = db.search("select * from salary where ym='"+d+"'");
                if (rs.next()) {
                    String path = "C:\\ProgramData\\supercity\\2\\salarypaymet.jrxml";
                    JasperReport jr = JasperCompileManager.compileReport(path);
                    Map m = new HashMap<String, Object>();
                    m.put("dt", d);
                    m.put("mn", mnth);
                    JasperPrint jp = JasperFillManager.fillReport(jr, m, db.con());
                    JasperViewer.viewReport(jp, false);
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "No data in this month", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);

                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void yActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Main.mp.removeAll();
        Main.mp.revalidate();
        run r=new run();
        Main.mp.add(r);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void yeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yeKeyTyped
         char c = evt.getKeyChar();
        if (c >= '0' && c <= '9') {
            
        } else {
            evt.consume();

        }
    }//GEN-LAST:event_yeKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton a;
    private javax.swing.JRadioButton a1;
    private javax.swing.JRadioButton a2;
    private javax.swing.JRadioButton b;
    private javax.swing.JRadioButton b1;
    private javax.swing.JRadioButton b2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JRadioButton c;
    private javax.swing.JRadioButton c1;
    private javax.swing.JRadioButton c2;
    private javax.swing.JRadioButton d;
    private javax.swing.JRadioButton d1;
    private javax.swing.JRadioButton d2;
    private javax.swing.JRadioButton e1;
    private javax.swing.JRadioButton e2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> m;
    private javax.swing.JTextField y;
    private javax.swing.JTextField ye;
    // End of variables declaration//GEN-END:variables

    private void loadtype() {
        try {
            jComboBox1.removeAllItems();
            ResultSet rs = db.search("select * from type");
            while (rs.next()) {
                jComboBox1.addItem(rs.getString("tname"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
