/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodcity;

import static foodcity.Main.mdatee;
import static foodcity.Main.mtime;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author Samith
 */
public class secinv extends javax.swing.JFrame {

    CardLayout cl;
    public secinv() {
        initComponents();
        det();
        cl=new CardLayout();
        pn.setLayout(cl);
        pn.removeAll();;
        pn.revalidate();
        invoice i=new  invoice();
        pn.add(i);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        pn = new javax.swing.JPanel();
        lg = new javax.swing.JLabel();
        tm = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButton1.setText("LOG OUT");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        javax.swing.GroupLayout pnLayout = new javax.swing.GroupLayout(pn);
        pn.setLayout(pnLayout);
        pnLayout.setHorizontalGroup(
            pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
        );
        pnLayout.setVerticalGroup(
            pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        getContentPane().add(pn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 1070, 690));

        lg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lg.setForeground(new java.awt.Color(102, 255, 255));
        lg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lg.setText("jLabel2");
        getContentPane().add(lg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 210, 20));

        tm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tm.setForeground(new java.awt.Color(102, 255, 255));
        tm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tm.setText("jLabel2");
        getContentPane().add(tm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 210, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/Rotating_earth_(large).gif"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 210, 360));

        dt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dt.setForeground(new java.awt.Color(102, 255, 255));
        dt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dt.setText("jLabel2");
        getContentPane().add(dt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 210, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/mpp.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
       log l=new log();
       l.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(secinv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(secinv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(secinv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(secinv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new secinv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lg;
    public static javax.swing.JPanel pn;
    private javax.swing.JLabel tm;
    // End of variables declaration//GEN-END:variables

    private void det() {
        Timer t = new Timer(1000, new ActionListener() {
Date d;
SimpleDateFormat sdf;
            @Override
            public void actionPerformed(ActionEvent e) {
                d = new Date();
                sdf = new SimpleDateFormat("yyyy-MM-dd");
                dt.setText("" + sdf.format(d));
                sdf = new SimpleDateFormat("HH:mm:ss");
                tm.setText(sdf.format(d));
                lg.setText(log.empina);
            }
        });
        t.start();}
}
