/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodcity;

import java.awt.Color;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author User
 */
public class stockadd extends javax.swing.JPanel {

    int tblclicked;
    String ido;

    public stockadd() {
        initComponents();
        tblclicked = 0;
        ido = "";
        gengrnid();
        jButton1.setEnabled(false);
        jList2.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel25 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        sid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        iid = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jLabel12 = new javax.swing.JLabel();
        de = new javax.swing.JLabel();
        up = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        st = new javax.swing.JTextField();
        dv = new javax.swing.JLabel();
        discount = new javax.swing.JTextField();
        value = new javax.swing.JLabel();
        qty = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        sname = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        t = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        invdiscount = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        grnid = new javax.swing.JLabel();
        nettotal = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ed = new com.toedter.calendar.JDateChooser();
        md = new com.toedter.calendar.JDateChooser();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Calibri Light", 1, 20)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("A D D  S T O C K");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 360, 20));

        jLabel4.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Po ID :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, 20));

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 110, 140));

        sid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sidKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sidKeyTyped(evt);
            }
        });
        add(sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 110, 30));

        jLabel9.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Item ID:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Grn ID:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, -1));

        iid.setEditable(false);
        iid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iidActionPerformed(evt);
            }
        });
        iid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                iidKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                iidKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                iidKeyTyped(evt);
            }
        });
        add(iid, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 130, -1));

        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jList2MouseEntered(evt);
            }
        });
        jScrollPane3.setViewportView(jList2);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 130, 40));

        jLabel12.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Description");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, -1, 20));

        de.setForeground(new java.awt.Color(255, 255, 255));
        add(de, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, 140, 20));

        up.setForeground(new java.awt.Color(255, 255, 255));
        add(up, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 140, 20));

        jLabel10.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Unite Price");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, -1, -1));

        jLabel14.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Qty:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, -1, -1));

        jLabel15.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("value:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, -1, 20));

        jLabel20.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Discount :");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, -1, 30));

        jLabel17.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Dis. value:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, -1, 30));

        jLabel19.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Exp Date");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 190, -1, 30));

        st.setEditable(false);
        add(st, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 110, 150, 30));

        dv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dv.setForeground(new java.awt.Color(255, 255, 255));
        add(dv, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 70, 150, 30));

        discount.setText("0");
        discount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountActionPerformed(evt);
            }
        });
        discount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                discountKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                discountKeyTyped(evt);
            }
        });
        add(discount, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, 150, 30));

        value.setForeground(new java.awt.Color(255, 255, 255));
        add(value, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 140, 20));

        qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyActionPerformed(evt);
            }
        });
        qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qtyKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qtyKeyTyped(evt);
            }
        });
        add(qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 140, -1));

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Calibri Light", 1, 20)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/addtv.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 220, 90, 50));

        jLabel5.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Supplier Name:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, 20));

        sname.setForeground(new java.awt.Color(255, 255, 255));
        add(sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 120, 20));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Description", "Unite Price", "Qty", "Value", "Discount", "Disvaluel", "Sob total", "M.date", "Exp.Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 840, 160));
        add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 150, -1));

        jLabel18.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Sub Tot");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, -1, -1));

        jLabel21.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Dis Price");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, 70, -1));

        jLabel22.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Dis value");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, -1, -1));

        invdiscount.setText("0");
        invdiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invdiscountActionPerformed(evt);
            }
        });
        invdiscount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                invdiscountKeyReleased(evt);
            }
        });
        add(invdiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, 150, -1));

        jLabel24.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Net tot");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, -1, -1));

        jButton8.setBackground(new java.awt.Color(51, 51, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/esv.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 450, 140, 40));

        jButton7.setBackground(new java.awt.Color(255, 51, 51));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/ecan.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 490, 140, 40));

        jButton6.setBackground(new java.awt.Color(51, 51, 255));
        jButton6.setFont(new java.awt.Font("Calibri Light", 1, 20)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/cltb.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 400, 160, 40));

        jButton5.setBackground(new java.awt.Color(51, 51, 255));
        jButton5.setFont(new java.awt.Font("Calibri Light", 1, 20)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/rm.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 340, 160, 40));

        jButton2.setBackground(new java.awt.Color(51, 51, 255));
        jButton2.setFont(new java.awt.Font("Calibri Light", 1, 20)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/ed.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 280, 160, 40));

        grnid.setForeground(new java.awt.Color(255, 255, 255));
        add(grnid, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 120, 20));

        nettotal.setForeground(new java.awt.Color(255, 255, 255));
        add(nettotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 500, 150, 20));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, 140, 20));
        add(ed, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 190, 150, 30));
        add(md, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 150, 150, 30));

        jLabel23.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Sub tot:");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 110, -1, 30));

        jLabel26.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Made date");
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 150, -1, 30));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item id", "Item Name", "Qty"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable2);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 250, 170));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/ll.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 540));
    }// </editor-fold>//GEN-END:initComponents

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        String name = jList1.getSelectedValue().toString();
        sid.setText(name);
        try {
            DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
            dtm.setRowCount(0);
            int x = jTable2.getSelectedRow();
            ResultSet rs = db.search("select a.*,b.* from(purchase_order_has_item a inner join item b on a.item_item_id=b.item_id) where purchase_order_po_id='" + sid.getText() + "'");
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString("item_id"));
                v.add(rs.getString("name"));
                v.add(rs.getString("qty"));
                dtm.addRow(v);

                ResultSet rs1 = db.search("select a.*,b.name from(purchase_order a inner join supplier b on a.supplier_sup_id=b.sup_id )where po_id='" + rs.getString("purchase_order_po_id") + "'");
                if (rs1.next()) {
                    sname.setText(rs1.getString("name"));
                    ido = rs1.getString("supplier_sup_id");
                }

            }
            iid.setEditable(true);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jList1MouseClicked

    private void sidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sidKeyReleased
        try {
            ResultSet rs = db.search("select * from purchase_order where po_id like '%" + sid.getText() + "%' and status='1'");
            Vector v = new Vector();

            while (rs.next()) {

                v.add(rs.getString("po_id"));

            }
            jList1.setListData(v);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_sidKeyReleased

    private void iidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iidActionPerformed
        qty.grabFocus();

    }//GEN-LAST:event_iidActionPerformed

    private void iidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_iidKeyPressed

    }//GEN-LAST:event_iidKeyPressed

    private void iidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_iidKeyReleased
        try {
            ResultSet rs = db.search("select a.*,b.* from (item a inner join purchase_order_has_item b on a.item_id=b.item_item_id)where item_id like '%" + iid.getText() + "%' and purchase_order_po_id='" + sid.getText() + "'");
            Vector v = new Vector();
            while (rs.next()) {
                v.add(rs.getString("item_id"));
            }
            jList2.setListData(v);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_iidKeyReleased

    private void discountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discountActionPerformed

    private void discountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_discountKeyReleased
        double d;
        double to = 0;
        if (discount.getText().length() == 0) {
            d = 0;
            to = Double.parseDouble(value.getText());
            double disp = d * to / 100;
            dv.setText("" + disp);
            double nettot = to - disp;
            st.setText("" + nettot);
        } else {
            d = Double.parseDouble(discount.getText());
            to = Double.parseDouble(value.getText());
            double disp = d * to / 100;
            dv.setText("" + disp);
            double nettot = to - disp;
            st.setText("" + nettot);
        }
    }//GEN-LAST:event_discountKeyReleased

    private void discountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_discountKeyTyped
        char c = evt.getKeyChar();
        if (c >= '0' && c <= '9') {

        } else {
            evt.consume();

        }
    }//GEN-LAST:event_discountKeyTyped

    private void qtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyKeyReleased
        jButton1.setEnabled(true);

        double b = 0;
        double a = Double.parseDouble(up.getText());
        double disc = 0;
        double tblqty = 0;
        double fldqty = 0;
        int lola = 0;
        for (int i = 0; i < jTable2.getRowCount(); i++) {
            System.out.println("lol");
            if (qty.getText().length() != 0) {
                System.out.println(jTable2.getValueAt(i, 0));
                if ((jTable2.getValueAt(i, 0).toString()).equals(iid.getText())) {
                    tblqty = Double.parseDouble(jTable2.getValueAt(i, 2).toString());
                    fldqty = Double.parseDouble(qty.getText());
                    System.out.println(tblqty);
                    if (tblqty >= fldqty) {
                        lola = 1;
                    }
                }
            }
        }
        if (lola == 1) {
            jButton1.setEnabled(true);
        } else {
           
            jButton1.setEnabled(false);
        }

        if (qty.getText().length() != 0) {
            b = Double.parseDouble(qty.getText());
        }

        double c = a * b;
        value.setText("" + c);
        if (discount.getText().length() == 0) {
            disc = 0;
        } else {
            disc = Double.parseDouble(discount.getText().toString());
        }
        double discv = c * disc / 100;
        dv.setText("" + discv);
        double dv = c - discv;
        st.setText("" + dv);


    }//GEN-LAST:event_qtyKeyReleased

    private void qtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyKeyTyped
        qty.setBackground(Color.WHITE);
        char c = evt.getKeyChar();
        if (c >= '0' && c <= '9') {

        } else {
            evt.consume();

        }
    }//GEN-LAST:event_qtyKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int check = 0;
        if (iid.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Please enter item id", "Error", JOptionPane.ERROR_MESSAGE);
            iid.grabFocus();
        } else if (qty.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Please enter qty", "Error", JOptionPane.ERROR_MESSAGE);
            qty.grabFocus();
        } else if (st.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Please enter qty", "Error", JOptionPane.ERROR_MESSAGE);
            qty.grabFocus();
        } else if (md.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Please set made date", "Error", JOptionPane.ERROR_MESSAGE);

        } else if (ed.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Please set exp date", "Error", JOptionPane.ERROR_MESSAGE);

        } else {
            int x = jTable1.getRowCount();

            if (x == 0) {
                DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
                Vector v = new Vector();
                v.add(iid.getText());
                v.add(de.getText());
                v.add(up.getText());
                v.add(qty.getText());
                v.add(value.getText());
                v.add(discount.getText());
                v.add(dv.getText());
                v.add(st.getText());
                Date d1 = md.getDate();
                Date d2 = ed.getDate();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                v.add(sdf.format(d1));
                v.add(sdf.format(d2));
                dtm.addRow(v);

                clearing();
            } else {
                String id = "";
                for (int i = 0; i < jTable1.getRowCount(); i++) {
                    id = jTable1.getValueAt(i, 0).toString();
                    if (id.equals(iid.getText())) {
                        check = 1;

                        double uprice = Double.parseDouble(jTable1.getValueAt(i, 2).toString());
                        double avbqt = Double.parseDouble(jTable1.getValueAt(i, 3).toString());

                        double nqty = Double.parseDouble(qty.getText());
                        double a = avbqt + nqty;
                        double val = uprice * a;
                        jTable1.setValueAt(a, i, 3);
                        jTable1.setValueAt(val, i, 4);
                        clearing();
                        double dis = Double.parseDouble(jTable1.getValueAt(i, 5).toString());
                        double dv = a * dis / 100;
                        jTable1.setValueAt(dv, i, 6);
                        val = val - dv;
                        jTable1.setValueAt(val, i, 7);

                    }

                }
                if (check == 0) {
                    DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
                    Vector v = new Vector();
                    v.add(iid.getText());
                    v.add(de.getText());
                    v.add(up.getText());
                    v.add(qty.getText());
                    v.add(value.getText());
                    v.add(discount.getText());
                    v.add(dv.getText());
                    v.add(st.getText());
                    Date d1 = md.getDate();
                    Date d2 = ed.getDate();
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                    v.add(sdf.format(d1));
                    v.add(sdf.format(d2));
                    dtm.addRow(v);

                    clearing();
                }
                jButton1.setEnabled(false);

            }

        }
        int rc = jTable1.getRowCount();
        double st = 0;
        if (rc > 0) {
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                st = st + Double.parseDouble(jTable1.getValueAt(i, 7).toString());
            }
            t.setText("" + st);

        }
        double disc = 0;
        double discv = 0;
        double nettoti = 0;
        if (invdiscount.getText().length() == 0) {

        } else {
            disc = Double.parseDouble(invdiscount.getText());

        }

        discv = disc * st / 100;
        jLabel6.setText("" + discv);
        nettoti = st - discv;
        nettotal.setText("" + nettoti);
        DefaultListModel model = new DefaultListModel();
                model.clear();
                jList1.setModel(model);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        tblclicked = 1;
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (tblclicked == 1) {
            int x = jTable1.getSelectedRow();
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.removeRow(x);
        }
        tblclicked = 0;
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        tblclicked = 0;
    }//GEN-LAST:event_jButton6ActionPerformed

    private void invdiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invdiscountActionPerformed
        double d1 = Double.parseDouble(t.getText());
        double d2 = Double.parseDouble(invdiscount.getText());
        double d3 = d1 * (100 - d2) / 100;
        nettotal.setText("" + d3);

    }//GEN-LAST:event_invdiscountActionPerformed

    private void invdiscountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_invdiscountKeyReleased
        double st = 0;
        double disc = 0;
        double discv = 0;
        double nettoti = 0;
        if (t.getText().length() == 0) {
        } else {
            st = Double.parseDouble(t.getText());
        }
        if (invdiscount.getText().length() == 0) {

        } else {
            disc = Double.parseDouble(invdiscount.getText());
        }
        discv = disc * st / 100;
        jLabel6.setText("" + discv);
        nettoti = st - discv;
        nettotal.setText("" + nettoti);
    }//GEN-LAST:event_invdiscountKeyReleased

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (nettotal.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Plese add item first");

        } else {
            try {
                double st = Double.parseDouble(t.getText().toString());
                double dis = 0;
                double disv = Double.parseDouble(jLabel6.getText().toString());
                double nt = Double.parseDouble(nettotal.getText().toString());

                if (invdiscount.getText().length() == 0) {
                } else {
                    dis = Double.parseDouble(invdiscount.getText().toString());
                }
                double tk=Double.parseDouble(nettotal.getText());
                db.iud("update purchase_order set status='0'where po_id='" + sid.getText() + "'");
                db.iud("update po_pay set amount='"+tk+"' where purchase_order_po_id='"+sid.getText()+"'");
                db.iud("insert into grn(grn_id,date,total,discount,dis_value,net_tot,supplier_sup_id,emp_emp_id,purchase_order_po_id) "
                        + "values('" + grnid.getText() + "','" + Main.mdatee.getText() + "','" + st + "','" + dis + "','" + disv + "','" + nt + "','" + ido + "','"+log.empido+"','"+sid.getText()+"')");
                for (int i = 0; i < jTable1.getRowCount(); i++) {
                    String id = jTable1.getValueAt(i, 0).toString();
                    double qty = Double.parseDouble(jTable1.getValueAt(i, 3).toString());
                    double tot = Double.parseDouble(jTable1.getValueAt(i, 4).toString());
                    double disc = Double.parseDouble(jTable1.getValueAt(i, 5).toString());
                    double stot = Double.parseDouble(jTable1.getValueAt(i, 7).toString());
                    String md = jTable1.getValueAt(i, 8).toString();
                    String ed = jTable1.getValueAt(i, 9).toString();
                    db.iud("insert into item_has_grn(item_item_id,grn_grn_id,qty,tot,discount,subtot,made_date,exp_date) "
                            + "value('" + id + "','" + grnid.getText() + "','" + qty + "','" + tot + "','" + disc + "','" + stot + "','" + md + "','" + ed + "')");
                    ResultSet rs = db.search("select * from stock where item_item_id='" + id + "'");
                    if (rs.next()) {
                        double qt = Double.parseDouble(rs.getString("qty"));
                        qt = qty + qt;
                        db.iud("update stock set qty='" + qt + "' where item_item_id='" + id + "' ");
                        double tt=Double.parseDouble(nettotal.getText());
                        
                    } else {
                        System.out.println("awlll");
                    }
                   
                }
                 reporta();
                    JOptionPane.showMessageDialog(this, "Success");
                    sid.setText(null);
                    jList1.setVisible(false);
                
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        clearing();
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);

        gengrnid();
        t.setText(null);
        invdiscount.setText("" + 0);
        jLabel6.setText(null);
        nettotal.setText(null);
        jList2.setVisible(false);
        iid.setEditable(false);

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        clearing();
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);

        gengrnid();
        t.setText(null);
        invdiscount.setText("" + 0);
        jLabel6.setText(null);
        nettotal.setText(null);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jList2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jList2MouseEntered

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        String name = jList2.getSelectedValue().toString();
        iid.setText(name);
        itemsearch(name);
        qty.grabFocus();
        DefaultListModel model = new DefaultListModel();
        model.clear();
        jList2.setModel(model);
        
    }//GEN-LAST:event_jList2MouseClicked

    private void qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyActionPerformed
        discount.grabFocus();
    }//GEN-LAST:event_qtyActionPerformed

    private void sidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sidKeyTyped
        jList1.setVisible(true);
    }//GEN-LAST:event_sidKeyTyped

    private void iidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_iidKeyTyped
        jList2.setVisible(true);
    }//GEN-LAST:event_iidKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel de;
    private javax.swing.JTextField discount;
    private javax.swing.JLabel dv;
    private com.toedter.calendar.JDateChooser ed;
    private javax.swing.JLabel grnid;
    private javax.swing.JTextField iid;
    private javax.swing.JTextField invdiscount;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private com.toedter.calendar.JDateChooser md;
    private javax.swing.JLabel nettotal;
    private javax.swing.JTextField qty;
    private javax.swing.JTextField sid;
    private javax.swing.JLabel sname;
    private javax.swing.JTextField st;
    private javax.swing.JTextField t;
    private javax.swing.JLabel up;
    private javax.swing.JLabel value;
    // End of variables declaration//GEN-END:variables

    private void supsearch(String id) {
        try {
            ResultSet rs = db.search("select * from supplier where sup_id='" + id + "'");
            if (rs.next()) {
                sname.setText(rs.getString("name"));
                sid.setText(rs.getString("sup_id"));
            } else {
                JOptionPane.showMessageDialog(this, "Wrong supplier id");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void clearing() {
        iid.setText(null);
        de.setText(null);
        up.setText(null);
        qty.setText(null);
        value.setText(null);
        discount.setText("" + 0);
        dv.setText(null);
        st.setText(null);
        md.setDate(null);
        ed.setDate(null);
        DefaultTableModel dtm=(DefaultTableModel)jTable2.getModel();
        dtm.setRowCount(0);
    }

    private void itemsearch(String id) {
        try {
            ResultSet rs = db.search("select * from item where item_id='" + id + "'");
            if (rs.next()) {
                de.setText(rs.getString("name"));
                up.setText(rs.getString("unit_Price"));
                iid.setText(rs.getString("item_id"));
            } else {
                JOptionPane.showMessageDialog(this, "Wrong supplier id");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void gengrnid() {
        try {
            ResultSet rs = db.search("select count(grn_id) as x from grn");

            if (rs.next()) {

                //string ekak int kalannaa
                int x = Integer.parseInt(rs.getString("x"));
                x++;
                if (x < 10) {

                    grnid.setText("GRN0" + x);
                } else if (x < 100) {

                    grnid.setText("GRN0" + x);
                } else {

                    grnid.setText("GRN" + x);
                }

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void reporta() {
         try {
            String p="C:\\ProgramData\\supercity\\2\\grn.jrxml";
            JasperReport jr=JasperCompileManager.compileReport(p);
            Map m=new HashMap<String, Object>();
            m.put("id", grnid.getText());
            JasperPrint  jp=JasperFillManager.fillReport(jr, m,db.con());
            JasperViewer.viewReport(jp,false);
        } catch (Exception e) {
        e.printStackTrace();
        }
 }
}
