/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodcity;

import static foodcity.Main.mp;
import java.awt.CardLayout;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Probosha
 */
public class Supplier extends javax.swing.JPanel {

    CardLayout cl;
    public Supplier() {
        initComponents();
       
        cl=new CardLayout();
        supmp.setLayout(cl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        supmp = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Prototype", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("S U P P L I E R   M A I N T A I N");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 30));

        supmp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/sp.png"))); // NOI18N
        supmp.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 540));

        add(supmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 1040, 540));

        jButton1.setBackground(new java.awt.Color(255, 51, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/editsup.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 50, 440, -1));

        jButton3.setBackground(new java.awt.Color(255, 51, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/addsup.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 50, 440, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/cncl.png"))); // NOI18N
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 60, 70, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/secpnl.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 690));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       itcheck();
        
        
      
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       supmp.removeAll();
        supmp.revalidate();
       // try {
            Editsup esup=new Editsup();
            supmp.add(esup);
            
       // } catch (Exception e) {
//            Logger.getLogger(Supplier.class.getName()).log(Level.SEVERE,null, e);
//        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Main.mp.removeAll();
       Main.mp.revalidate();
       run r=new run();
       Main.mp.add(r);
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JPanel supmp;
    // End of variables declaration//GEN-END:variables

    private void itcheck() {
         try {
             ResultSet rs = db.search("select count(item_id) as x from item");
            if (rs.next()) {
               
                int x = Integer.parseInt(rs.getString("x"));
                if (x == 0) {
                    
                    JOptionPane.showMessageDialog(this, "You haven't item please add item first", "Warning", JOptionPane.WARNING_MESSAGE);
                    mp.removeAll();
                    mp.revalidate();
                    item e = new item();
                    mp.add(e);
                } else {
                  supmp.removeAll();
        supmp.revalidate();
        try {
            supadd sup=new supadd();
            supmp.add(sup);
        } catch (Exception ex) {
            Logger.getLogger(Supplier.class.getName()).log(Level.SEVERE, null, ex);
        }
                }
            }
            
        } catch (Exception e) {
        e.printStackTrace();
        } }

   
}
